
"""
biochar_app.config

Curated public config exports.
"""

from .core import (
    DEFAULT_GRANULARITY,
    DEFAULT_GSEASON_PERIODS,
    DEFAULT_SENSOR_DEPTH_CODE,
    DEFAULT_YEAR,
    LOGGER_LOCATIONS,
    PLOT_COLORS,
    SENSOR_DEPTH_CODES,
    SENSOR_DEPTH_LABELS,
    SENSOR_DEPTH_VALUES,
    STRIPS,
    TITLE_FONT_SIZE,
    TRACE_CHOICES,
    YEARS,
)

from .experiment_config import (
    CS650_SENSING_VOLUME_CM3,
    CS650_VERTICAL_SENSITIVITY_RADIUS_IN,
    REPRESENTED_LAYER_THICKNESS_IN_BY_DEPTH_INDEX,
    SENSOR_CENTERED_LAYER_BOUNDS_IN_BY_DEPTH_INDEX,
    THREE_SENSOR_PROFILE_LOWER_BOUND_IN,
    THREE_SENSOR_PROFILE_NOMINAL_THICKNESS_IN,
    THREE_SENSOR_PROFILE_UPPER_BOUND_IN,
)

from .pakbus import (
    PAKBUS,
)

from .paths import (
    BASE_DIR,
    DATA_PROCESSED_DIR,
    DATA_RAW_DIR,
    LAB_TESTS_RAW_DIR,
    PARQUET_DIR,
    PARQUET_SUMMARY_15MIN_DIR,
    SOIL_CHEM_PROCESSED_DIR,
    WARD_MASTER_NIR_CSV,
    BIOCHAR_MASTER_WORKBOOK,
    WARD_MASTER_SOILBIO_CSV,
    WARD_MASTER_SOILCHEM_CSV,
    ensure_analysis_output_directories,
    irrigation_analysis_paths,
)

from .thresholds import (
    DEFAULT_BAD_VALUE_THRESHOLD,
)

from .units import (
    METRIC_UNITS,
    UNIT_CONVERSIONS,
    US_UNITS,
    DEFAULT_UNITS,
)

__all__ = [
    "BASE_DIR",
    "DEFAULT_GRANULARITY",
    "DEFAULT_GSEASON_PERIODS",
    "DEFAULT_SENSOR_DEPTH_CODE",
    "DEFAULT_YEAR",
    "DEFAULT_UNITS",
    "LOGGER_LOCATIONS",
    "CS650_SENSING_VOLUME_CM3",
    "CS650_VERTICAL_SENSITIVITY_RADIUS_IN",
    "REPRESENTED_LAYER_THICKNESS_IN_BY_DEPTH_INDEX",
    "SENSOR_CENTERED_LAYER_BOUNDS_IN_BY_DEPTH_INDEX",
    "SENSOR_DEPTH_CODES",
    "SENSOR_DEPTH_LABELS",
    "SENSOR_DEPTH_VALUES",
    "STRIPS",
    "THREE_SENSOR_PROFILE_LOWER_BOUND_IN",
    "THREE_SENSOR_PROFILE_NOMINAL_THICKNESS_IN",
    "THREE_SENSOR_PROFILE_UPPER_BOUND_IN",
    "YEARS",
    "PAKBUS",
    "DATA_PROCESSED_DIR",
    "DATA_RAW_DIR",
    "LAB_TESTS_RAW_DIR",
    "PARQUET_DIR",
    "PARQUET_SUMMARY_15MIN_DIR",
    "PLOT_COLORS",
    "SOIL_CHEM_PROCESSED_DIR",
    "DEFAULT_BAD_VALUE_THRESHOLD",
    "METRIC_UNITS",
    "TITLE_FONT_SIZE",
    "TRACE_CHOICES",
    "UNIT_CONVERSIONS",
    "US_UNITS",
    "BIOCHAR_MASTER_WORKBOOK",
    "WARD_MASTER_SOILBIO_CSV",
    "WARD_MASTER_SOILCHEM_CSV",
    "WARD_MASTER_NIR_CSV",
    "ensure_analysis_output_directories",
    "irrigation_analysis_paths",
]
