"""
Central metadata registry for lab variables used in the Biochar Fruita CSU dashboard.

This file should describe existing standardized column names.

Do not rename source columns here.
"""

from __future__ import annotations

LAB_VARIABLE_METADATA = {

    'actinomycetes_biomass': {'display_label': 'Actinomycetes Biomass',
                           'source_label': 'Actinomycetes',
                           'dataset_family': 'soil_biology_plfa',
                           'group': 'Functional Group Biomass',
                           'units': 'ng/g',
                           'value_type': 'biomass',
                           'definition': 'Estimated biomass of actinomycetes based on PLFA '
                                         'biomarkers.',
                           'interpretation_note': 'Actinomycetes are bacteria often associated '
                                                  'with decomposition of complex organic '
                                                  'materials.',
                           'source_reference_group': 'Ward PLFA Biological Report',
                           'aliases': ['actinomycete biomass', 'actinomycetes'],
                           'related_terms': ['bacteria',
                                             'decomposition',
                                             'plfa',
                                             'microbial_biomass']},
 'actinomycetes_pct': {'display_label': 'Actinomycetes (%)',
                       'source_label': 'Actinomycetes %',
                       'dataset_family': 'soil_biology_plfa',
                       'group': 'Relative Abundance',
                       'units': '%',
                       'value_type': 'percent',
                       'definition': 'Relative abundance of actinomycetes as a percentage of total '
                                     'microbial biomass.',
                       'interpretation_note': 'This is a relative abundance measure rather than an '
                                              'absolute biomass value.',
                       'source_reference_group': 'Ward PLFA Biological Report',
                       'aliases': ['actinomycetes percent', 'actinomycete percent'],
                       'related_terms': ['actinomycetes_biomass', 'bacteria', 'plfa']},
 'arbuscular_mycorrhizal_biomass': {'display_label': 'Arbuscular Mycorrhizal Fungi Biomass',
                                    'source_label': 'Arbuscular Mycorrhizal',
                                    'dataset_family': 'soil_biology_plfa',
                                    'group': 'Functional Group Biomass',
                                    'units': 'ng/g',
                                    'value_type': 'biomass',
                                    'definition': 'Estimated biomass of arbuscular mycorrhizal '
                                                  'fungi based on PLFA biomarkers.',
                                    'interpretation_note': 'Arbuscular mycorrhizal fungi are '
                                                           'plant-associated fungi involved in '
                                                           'nutrient and water uptake '
                                                           'relationships.',
                                    'source_reference_group': 'Ward PLFA Biological Report',
                                    'aliases': ['AMF biomass',
                                                'arbuscular mycorrhizal biomass',
                                                'mycorrhizal fungi biomass'],
                                    'related_terms': ['fungi',
                                                      'mycorrhizae',
                                                      'plfa',
                                                      'microbial_biomass']},
 'arbuscular_mycorrhizal_pct': {'display_label': 'Arbuscular Mycorrhizal Fungi (%)',
                                'source_label': 'Arbuscular Mycorrhizal %',
                                'dataset_family': 'soil_biology_plfa',
                                'group': 'Relative Abundance',
                                'units': '%',
                                'value_type': 'percent',
                                'definition': 'Relative abundance of arbuscular mycorrhizal fungi '
                                              'as a percentage of total microbial biomass.',
                                'interpretation_note': 'Represents the proportional abundance of '
                                                       'arbuscular mycorrhizal fungi within the '
                                                       'microbial community.',
                                'source_reference_group': 'Ward PLFA Biological Report',
                                'aliases': ['AMF percent',
                                            'arbuscular mycorrhizal percent',
                                            'mycorrhizal fungi percent'],
                                'related_terms': ['arbuscular_mycorrhizal_biomass',
                                                  'fungi',
                                                  'mycorrhizae',
                                                  'plfa']},
 'bacteria_pct': {'display_label': 'Bacteria (%)',
                  'source_label': 'Bacteria %',
                  'dataset_family': 'soil_biology_plfa',
                  'group': 'Relative Abundance',
                  'units': '%',
                  'value_type': 'percent',
                  'definition': 'Bacterial PLFA abundance as a percentage of total microbial '
                                'biomass.',
                  'interpretation_note': 'This is a relative abundance measure, not an absolute '
                                         'biomass value.',
                  'source_reference_group': 'Ward PLFA Biological Report',
                  'aliases': ['bacteria percent', 'bacterial relative abundance'],
                  'related_terms': ['bacteria', 'relative_abundance', 'plfa']},
 'fungi_bacteria': {'display_label': 'Fungi:Bacteria Ratio',
                    'source_label': 'Fungi:Bacteria',
                    'dataset_family': 'soil_biology_plfa',
                    'group': 'Ratios and Indices',
                    'units': None,
                    'value_type': 'ratio',
                    'definition': 'Ratio of fungal biomass to bacterial biomass.',
                    'interpretation_note': 'Higher values indicate greater fungal dominance '
                                           'relative to bacteria.',
                    'source_reference_group': 'Ward PLFA Biological Report',
                    'aliases': ['fungi bacteria ratio', 'fungal bacterial ratio'],
                    'related_terms': ['fungi', 'bacteria', 'plfa_ratio']},
 'gram_neg_biomass': {'display_label': 'Gram Negative Bacterial Biomass',
                      'source_label': 'Gram -',
                      'dataset_family': 'soil_biology_plfa',
                      'group': 'Functional Group Biomass',
                      'units': 'ng/g',
                      'value_type': 'biomass',
                      'definition': 'Estimated biomass of gram-negative bacteria based on PLFA '
                                    'biomarkers.',
                      'interpretation_note': 'Higher values indicate greater abundance of '
                                             'gram-negative bacterial biomass.',
                      'source_reference_group': 'Ward PLFA Biological Report',
                      'aliases': ['gram negative biomass', 'gram negative bacteria'],
                      'related_terms': ['bacteria', 'plfa', 'microbial_biomass']},
 'gram_neg_pct': {'display_label': 'Gram Negative Bacteria (%)',
                  'source_label': 'Gram - %',
                  'dataset_family': 'soil_biology_plfa',
                  'group': 'Relative Abundance',
                  'units': '%',
                  'value_type': 'percent',
                  'definition': 'Relative abundance of gram-negative bacteria as a percentage of '
                                'total microbial biomass.',
                  'interpretation_note': 'This represents proportional abundance rather than '
                                         'absolute biomass.',
                  'source_reference_group': 'Ward PLFA Biological Report',
                  'aliases': ['gram negative percent'],
                  'related_terms': ['bacteria', 'relative_abundance', 'plfa']},
 'gram_pos_biomass': {'display_label': 'Gram Positive Bacterial Biomass',
                      'source_label': 'Gram +',
                      'dataset_family': 'soil_biology_plfa',
                      'group': 'Functional Group Biomass',
                      'units': 'ng/g',
                      'value_type': 'biomass',
                      'definition': 'Estimated biomass of gram-positive bacteria based on PLFA '
                                    'biomarkers.',
                      'interpretation_note': 'Higher values indicate greater abundance of '
                                             'gram-positive bacterial biomass.',
                      'source_reference_group': 'Ward PLFA Biological Report',
                      'aliases': ['gram positive biomass', 'gram positive bacteria'],
                      'related_terms': ['bacteria', 'plfa', 'microbial_biomass']},
 'gram_pos_gram_neg_ratio': {'display_label': 'Gram Positive:Gram Negative Ratio',
                             'source_label': 'Gram+:Gram-',
                             'dataset_family': 'soil_biology_plfa',
                             'group': 'Ratios and Indices',
                             'units': None,
                             'value_type': 'ratio',
                             'definition': 'Ratio of gram-positive bacterial biomass to '
                                           'gram-negative bacterial biomass.',
                             'interpretation_note': 'Used as an indicator of microbial community '
                                                    'structure and potential stress response.',
                             'source_reference_group': 'Ward PLFA Biological Report',
                             'aliases': ['gram positive gram negative ratio',
                                         'gram+/gram- ratio',
                                         'gram_pos_gram'],
                             'related_terms': ['gram_pos_biomass',
                                               'gram_neg_biomass',
                                               'plfa_ratio']},
 'gram_pos_pct': {'display_label': 'Gram Positive Bacteria (%)',
                  'source_label': 'Gram + %',
                  'dataset_family': 'soil_biology_plfa',
                  'group': 'Relative Abundance',
                  'units': '%',
                  'value_type': 'percent',
                  'definition': 'Relative abundance of gram-positive bacteria as a percentage of '
                                'total microbial biomass.',
                  'interpretation_note': 'This represents proportional abundance rather than '
                                         'absolute biomass.',
                  'source_reference_group': 'Ward PLFA Biological Report',
                  'aliases': ['gram positive percent'],
                  'related_terms': ['bacteria', 'relative_abundance', 'plfa']},
 'monounsaturated': {'display_label': 'Monounsaturated Fatty Acid Biomass',
                     'source_label': 'MonoUnsaturated',
                     'dataset_family': 'soil_biology_plfa',
                     'group': 'Fatty Acid Pools',
                     'units': 'ng/g',
                     'value_type': 'biomass',
                     'definition': 'Estimated biomass associated with monounsaturated fatty acid '
                                   'PLFA biomarkers.',
                     'interpretation_note': 'Monounsaturated fatty acid pools may reflect shifts '
                                            'in microbial community composition and physiological '
                                            'condition.',
                     'source_reference_group': 'Ward PLFA Biological Report',
                     'aliases': ['mono unsaturated', 'monounsaturated fatty acids'],
                     'related_terms': ['unsaturated',
                                       'polyunsaturated',
                                       'monounsaturated_polyunsaturated_ratio',
                                       'plfa']},
 'monounsaturated_polyunsaturated_ratio': {'display_label': 'Monounsaturated:Polyunsaturated Fatty '
                                                            'Acid Ratio',
                                           'source_label': 'Mono:Poly',
                                           'dataset_family': 'soil_biology_plfa',
                                           'group': 'Ratios and Indices',
                                           'units': None,
                                           'value_type': 'ratio',
                                           'definition': 'Ratio of monounsaturated fatty acid '
                                                         'biomass to polyunsaturated fatty acid '
                                                         'biomass.',
                                           'interpretation_note': 'Used as a PLFA stress and '
                                                                  'microbial community structure '
                                                                  'indicator.',
                                           'source_reference_group': 'Ward PLFA Biological Report',
                                           'aliases': ['mono_poly',
                                                       'mono poly ratio',
                                                       'MUFA:PUFA ratio'],
                                           'related_terms': ['monounsaturated',
                                                             'polyunsaturated',
                                                             'plfa_ratio']},
 'polyunsaturated': {'display_label': 'Polyunsaturated Fatty Acid Biomass',
                     'source_label': 'PolyUnsaturated',
                     'dataset_family': 'soil_biology_plfa',
                     'group': 'Fatty Acid Pools',
                     'units': 'ng/g',
                     'value_type': 'biomass',
                     'definition': 'Estimated biomass associated with polyunsaturated fatty acid '
                                   'PLFA biomarkers.',
                     'interpretation_note': 'Polyunsaturated fatty acid pools are often associated '
                                            'with fungal and eukaryotic microbial components.',
                     'source_reference_group': 'Ward PLFA Biological Report',
                     'aliases': ['poly unsaturated', 'polyunsaturated fatty acids'],
                     'related_terms': ['unsaturated',
                                       'monounsaturated',
                                       'monounsaturated_polyunsaturated_ratio',
                                       'plfa']},
 'predator_prey': {'display_label': 'Predator:Prey Ratio',
                   'source_label': 'Predator:Prey',
                   'dataset_family': 'soil_biology_plfa',
                   'group': 'Ratios and Indices',
                   'units': None,
                   'value_type': 'ratio',
                   'definition': 'Ratio of predator-associated PLFA biomass to prey-associated '
                                 'PLFA biomass.',
                   'interpretation_note': 'Used as an indicator of microbial food-web structure. '
                                          'Higher values may indicate greater predator '
                                          'representation relative to prey groups.',
                   'source_reference_group': 'Ward PLFA Biological Report',
                   'aliases': ['predator prey ratio', 'predator:prey'],
                   'related_terms': ['protozoa_biomass', 'bacteria', 'fungi', 'plfa_ratio']},
 'protozoa_biomass': {'display_label': 'Protozoa Biomass',
                      'source_label': 'Protozoa',
                      'dataset_family': 'soil_biology_plfa',
                      'group': 'Functional Group Biomass',
                      'units': 'ng/g',
                      'value_type': 'biomass',
                      'definition': 'Estimated protozoa-associated biomass based on PLFA '
                                    'biomarkers.',
                      'interpretation_note': 'Protozoa are microbial predators and can indicate '
                                             'soil food-web activity.',
                      'source_reference_group': 'Ward PLFA Biological Report',
                      'aliases': ['protozoa biomass', 'protozoan biomass'],
                      'related_terms': ['protozoa', 'predator_prey', 'plfa', 'microbial_biomass']},
 'protozoan_pct': {'display_label': 'Protozoa (%)',
                   'source_label': 'Protozoa %',
                   'dataset_family': 'soil_biology_plfa',
                   'group': 'Relative Abundance',
                   'units': '%',
                   'value_type': 'percent',
                   'definition': 'Relative abundance of protozoa-associated biomarkers as a '
                                 'percentage of total microbial biomass.',
                   'interpretation_note': 'Protozoa are microbial predators and can reflect soil '
                                          'food-web structure.',
                   'source_reference_group': 'Ward PLFA Biological Report',
                   'aliases': ['protozoa percent', 'protozoan percent'],
                   'related_terms': ['protozoa_biomass', 'predator_prey', 'plfa']},
 'rhizobia_biomass': {'display_label': 'Rhizobia Biomass',
                      'source_label': 'Rhizobia',
                      'dataset_family': 'soil_biology_plfa',
                      'group': 'Functional Group Biomass',
                      'units': 'ng/g',
                      'value_type': 'biomass',
                      'definition': 'Estimated biomass of rhizobia-associated microbial '
                                    'biomarkers.',
                      'interpretation_note': 'Rhizobia are bacteria commonly associated with '
                                             'nitrogen-fixing relationships with legumes.',
                      'source_reference_group': 'Ward PLFA Biological Report',
                      'aliases': ['rhizobia biomass', 'rhizobial biomass'],
                      'related_terms': ['bacteria',
                                        'nitrogen_fixation',
                                        'plfa',
                                        'microbial_biomass']},
 'rhizobia_pct': {'display_label': 'Rhizobia (%)',
                  'source_label': 'Rhizobia %',
                  'dataset_family': 'soil_biology_plfa',
                  'group': 'Relative Abundance',
                  'units': '%',
                  'value_type': 'percent',
                  'definition': 'Relative abundance of rhizobia-associated biomarkers as a '
                                'percentage of total microbial biomass.',
                  'interpretation_note': 'This represents proportional abundance rather than '
                                         'absolute biomass.',
                  'source_reference_group': 'Ward PLFA Biological Report',
                  'aliases': ['rhizobia percent'],
                  'related_terms': ['rhizobia_biomass', 'bacteria', 'plfa']},
 'saprophytes_biomass': {'display_label': 'Saprophyte Biomass',
                         'source_label': 'Saprophytes',
                         'dataset_family': 'soil_biology_plfa',
                         'group': 'Functional Group Biomass',
                         'units': 'ng/g',
                         'value_type': 'biomass',
                         'definition': 'Estimated biomass of saprophytic organisms based on PLFA '
                                       'biomarkers.',
                         'interpretation_note': 'Saprophytes are associated with decomposition of '
                                                'dead organic matter.',
                         'source_reference_group': 'Ward PLFA Biological Report',
                         'aliases': ['saprophyte biomass', 'saprophytic biomass', 'saprophytes'],
                         'related_terms': ['fungi', 'decomposition', 'plfa', 'microbial_biomass']},
 'saprophytic_pct': {'display_label': 'Saprophytes (%)',
                     'source_label': 'Saprophytes %',
                     'dataset_family': 'soil_biology_plfa',
                     'group': 'Relative Abundance',
                     'units': '%',
                     'value_type': 'percent',
                     'definition': 'Relative abundance of saprophytic organisms as a percentage of '
                                   'total microbial biomass.',
                     'interpretation_note': 'Saprophytes are associated with decomposition of dead '
                                            'organic matter.',
                     'source_reference_group': 'Ward PLFA Biological Report',
                     'aliases': ['saprophyte percent', 'saprophytic percent'],
                     'related_terms': ['saprophytes_biomass', 'decomposition', 'fungi', 'plfa']},
 'saturated': {'display_label': 'Saturated Fatty Acid Biomass',
               'source_label': 'Saturated',
               'dataset_family': 'soil_biology_plfa',
               'group': 'Fatty Acid Pools',
               'units': 'ng/g',
               'value_type': 'biomass',
               'definition': 'Estimated biomass associated with saturated fatty acid PLFA '
                             'biomarkers.',
               'interpretation_note': 'Used in PLFA stress and community structure interpretation.',
               'source_reference_group': 'Ward PLFA Biological Report',
               'aliases': ['saturated fatty acids'],
               'related_terms': ['plfa', 'fatty_acids']},
 'saturated_unsaturated_ratio': {'display_label': 'Saturated:Unsaturated Fatty Acid Ratio',
                                 'source_label': 'Sat:Unsat',
                                 'dataset_family': 'soil_biology_plfa',
                                 'group': 'Ratios and Indices',
                                 'units': None,
                                 'value_type': 'ratio',
                                 'definition': 'Ratio of saturated fatty acid biomass to '
                                               'unsaturated fatty acid biomass.',
                                 'interpretation_note': 'Used as a PLFA stress and microbial '
                                                        'community structure indicator.',
                                 'source_reference_group': 'Ward PLFA Biological Report',
                                 'aliases': ['sat_unsat',
                                             'saturated unsaturated ratio',
                                             'saturated:unsaturated ratio'],
                                 'related_terms': ['saturated', 'unsaturated', 'plfa_ratio']},
 'total_bacteria_biomass': {'display_label': 'Total Bacterial Biomass',
                            'source_label': 'Total Bacteria',
                            'dataset_family': 'soil_biology_plfa',
                            'group': 'Functional Group Biomass',
                            'units': 'ng/g',
                            'value_type': 'biomass',
                            'definition': 'Estimated living bacterial biomass based on PLFA '
                                          'biomarkers.',
                            'interpretation_note': 'Higher values generally indicate greater '
                                                   'bacterial biomass.',
                            'source_reference_group': 'Ward PLFA Biological Report',
                            'aliases': ['total bacteria', 'bacterial biomass'],
                            'related_terms': ['bacteria', 'plfa', 'microbial_biomass']},
 'total_biomass': {'display_label': 'Total Living Microbial Biomass',
                   'dataset_family': 'soil_biology_plfa',
                   'group': 'Microbial Biomass',
                   'units': 'ng/g',
                   'value_type': 'biomass',
                   'definition': 'Total living microbial biomass estimated from PLFA biomarkers.',
                   'interpretation_note': 'Higher values generally indicate greater living '
                                          'microbial biomass.',
                   'source_reference_group': 'Ward PLFA Biological Report',
                   'aliases': ['Total Biomass', 'Total Living Microbial Biomass'],
                   'related_terms': ['plfa', 'microbial_biomass']},
 'total_fungi_biomass': {'display_label': 'Total Fungal Biomass',
                         'source_label': 'Total Fungi',
                         'dataset_family': 'soil_biology_plfa',
                         'group': 'Functional Group Biomass',
                         'units': 'ng/g',
                         'value_type': 'biomass',
                         'definition': 'Estimated total fungal biomass based on PLFA biomarkers.',
                         'interpretation_note': 'Higher values indicate greater fungal biomass in '
                                                'the soil microbial community.',
                         'source_reference_group': 'Ward PLFA Biological Report',
                         'aliases': ['total fungi biomass', 'fungal biomass', 'total fungi'],
                         'related_terms': ['fungi', 'plfa', 'microbial_biomass']},
 'total_fungi_pct': {'display_label': 'Total Fungi (%)',
                     'source_label': 'Total Fungi %',
                     'dataset_family': 'soil_biology_plfa',
                     'group': 'Relative Abundance',
                     'units': '%',
                     'value_type': 'percent',
                     'definition': 'Relative abundance of fungal biomass as a percentage of total '
                                   'microbial biomass.',
                     'interpretation_note': 'Higher values indicate greater fungal dominance '
                                            'within the microbial community.',
                     'source_reference_group': 'Ward PLFA Biological Report',
                     'aliases': ['fungi percent', 'fungal percent', 'total fungi percent'],
                     'related_terms': ['total_fungi_biomass', 'fungi', 'plfa']},
 'undifferentiated_biomass': {'display_label': 'Undifferentiated Microbial Biomass',
                              'source_label': 'Undifferentiated',
                              'dataset_family': 'soil_biology_plfa',
                              'group': 'Functional Group Biomass',
                              'units': 'ng/g',
                              'value_type': 'biomass',
                              'definition': 'Estimated PLFA biomass not assigned to a more '
                                            'specific microbial functional group.',
                              'interpretation_note': 'This category captures microbial biomass '
                                                     'that is not differentiated into the named '
                                                     'functional groups.',
                              'source_reference_group': 'Ward PLFA Biological Report',
                              'aliases': ['undifferentiated biomass',
                                          'unclassified microbial biomass'],
                              'related_terms': ['plfa', 'microbial_biomass']},
 'undifferentiated_pct': {'display_label': 'Undifferentiated Biomass (%)',
                          'source_label': 'Undifferentiated %',
                          'dataset_family': 'soil_biology_plfa',
                          'group': 'Relative Abundance',
                          'units': '%',
                          'value_type': 'percent',
                          'definition': 'Relative abundance of undifferentiated microbial biomass '
                                        'as a percentage of total microbial biomass.',
                          'interpretation_note': 'Represents microbial biomass not classified into '
                                                 'the named functional groups.',
                          'source_reference_group': 'Ward PLFA Biological Report',
                          'aliases': ['undifferentiated percent', 'unclassified biomass percent'],
                          'related_terms': ['undifferentiated_biomass',
                                            'plfa',
                                            'microbial_biomass']},
 'unsaturated': {'display_label': 'Unsaturated Fatty Acid Biomass',
                 'source_label': 'Unsaturated',
                 'dataset_family': 'soil_biology_plfa',
                 'group': 'Fatty Acid Pools',
                 'units': 'ng/g',
                 'value_type': 'biomass',
                 'definition': 'Estimated biomass associated with unsaturated fatty acid PLFA '
                               'biomarkers.',
                 'interpretation_note': 'Unsaturated fatty acid pools are commonly used in '
                                        'microbial community structure and physiological stress '
                                        'interpretation.',
                 'source_reference_group': 'Ward PLFA Biological Report',
                 'aliases': ['unsaturated fatty acids', 'unsaturated PLFA pool'],
                 'related_terms': ['saturated',
                                   'monounsaturated',
                                   'polyunsaturated',
                                   'saturated_unsaturated_ratio',
                                   'monounsaturated_polyunsaturated_ratio',
                                   'plfa']},

 "pre_16_1_w7c": {
     "display_label": "Pre 16:1 ω7c Biomarker",
     "source_label": "Pre 16:1 w7c",
     "dataset_family": "soil_biology_plfa",
     "group": "Stress Biomarkers",
     "units": "ng/g",
     "value_type": "biomass",
     "definition": "Estimated biomass associated with the 16:1 ω7c precursor PLFA biomarker.",
     "interpretation_note": "Used with cyclo 17:0 to calculate a PLFA stress ratio.",
     "source_reference_group": "Ward PLFA Biological Report",
     "aliases": ["pre 16:1 w7c", "16:1 w7c precursor"],
     "related_terms": ["cyclo_17_0", "pre_16_1w7c_cy17_0", "plfa_stress"],
 },

 "cyclo_17_0": {
     "display_label": "Cyclo 17:0 Biomarker",
     "source_label": "Cyclo 17:0",
     "dataset_family": "soil_biology_plfa",
     "group": "Stress Biomarkers",
     "units": "ng/g",
     "value_type": "biomass",
     "definition": "Estimated biomass associated with the cyclopropyl 17:0 PLFA biomarker.",
     "interpretation_note": "Used with pre 16:1 ω7c to calculate a PLFA stress ratio.",
     "source_reference_group": "Ward PLFA Biological Report",
     "aliases": ["cyclo 17:0", "cy17:0"],
     "related_terms": ["pre_16_1_w7c", "pre_16_1w7c_cy17_0", "plfa_stress"],
 },

 "pre_16_1w7c_cy17_0": {
     "display_label": "Pre 16:1 ω7c:Cyclo 17:0 Ratio",
     "source_label": "Pre 16:1w7c/Cy17:0",
     "dataset_family": "soil_biology_plfa",
     "group": "Stress Ratios",
     "units": None,
     "value_type": "ratio",
     "definition": "Ratio comparing the 16:1 ω7c precursor biomarker with cyclo 17:0.",
     "interpretation_note": "Used as a PLFA physiological stress indicator.",
     "source_reference_group": "Ward PLFA Biological Report",
     "aliases": ["pre 16:1w7c cy17:0 ratio", "16:1w7c/cy17:0"],
     "related_terms": ["pre_16_1_w7c", "cyclo_17_0", "plfa_stress"],
 },

 "pre_18_1_w7c": {
     "display_label": "Pre 18:1 ω7c Biomarker",
     "source_label": "Pre 18:1 w7c",
     "dataset_family": "soil_biology_plfa",
     "group": "Stress Biomarkers",
     "units": "ng/g",
     "value_type": "biomass",
     "definition": "Estimated biomass associated with the 18:1 ω7c precursor PLFA biomarker.",
     "interpretation_note": "Used with cyclo 19:0 to calculate a PLFA stress ratio.",
     "source_reference_group": "Ward PLFA Biological Report",
     "aliases": ["pre 18:1 w7c", "18:1 w7c precursor"],
     "related_terms": ["cyclo_19_0", "pre_18_1w7c_cy19_0", "plfa_stress"],
 },

 "cyclo_19_0": {
     "display_label": "Cyclo 19:0 Biomarker",
     "source_label": "Cyclo 19:0",
     "dataset_family": "soil_biology_plfa",
     "group": "Stress Biomarkers",
     "units": "ng/g",
     "value_type": "biomass",
     "definition": "Estimated biomass associated with the cyclopropyl 19:0 PLFA biomarker.",
     "interpretation_note": "Used with pre 18:1 ω7c to calculate a PLFA stress ratio.",
     "source_reference_group": "Ward PLFA Biological Report",
     "aliases": ["cyclo 19:0", "cy19:0"],
     "related_terms": ["pre_18_1_w7c", "pre_18_1w7c_cy19_0", "plfa_stress"],
 },

 "pre_18_1w7c_cy19_0": {
     "display_label": "Pre 18:1 ω7c:Cyclo 19:0 Ratio",
     "source_label": "Pre 18:1w7c/Cy19:0",
     "dataset_family": "soil_biology_plfa",
     "group": "Stress Ratios",
     "units": None,
     "value_type": "ratio",
     "definition": "Ratio comparing the 18:1 ω7c precursor biomarker with cyclo 19:0.",
     "interpretation_note": "Used as a PLFA physiological stress indicator.",
     "source_reference_group": "Ward PLFA Biological Report",
     "aliases": ["pre 18:1w7c cy19:0 ratio", "18:1w7c/cy19:0"],
     "related_terms": ["pre_18_1_w7c", "cyclo_19_0", "plfa_stress"],
 },

 "diversity_index": {
     "display_label": "Functional Group Diversity Index",
     "source_label": "Diversity Index",
     "dataset_family": "soil_biology_plfa",
     "group": "Ratios and Indices",
     "units": None,
     "value_type": "index",
     "definition": "Index summarizing microbial functional group diversity based on PLFA results.",
     "interpretation_note": "Higher values generally indicate greater microbial functional diversity.",
     "source_reference_group": "Ward PLFA Biological Report",
     "aliases": ["diversity index", "functional group diversity index"],
     "related_terms": ["plfa", "microbial_diversity"],
 },
    "moisture_pct": {
        "display_label": "Moisture",
        "source_label": "Moisture",
        "dataset_family": "hay_nir",
        "group": "Moisture & Dry Matter",
        "units": "%",
        "value_type": "percent",
        "definition": "Moisture content of the forage sample.",
        "interpretation_note": "Higher moisture means lower dry matter concentration in the submitted sample.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["moisture percent", "forage moisture"],
        "related_terms": ["dry_matter_pct", "hay_nir"],
    },

    "dry_matter_pct": {
        "display_label": "Dry Matter",
        "source_label": "Dry Matter",
        "dataset_family": "hay_nir",
        "group": "Moisture & Dry Matter",
        "units": "%",
        "value_type": "percent",
        "definition": "Dry matter content of the forage sample.",
        "interpretation_note": "Most forage nutrient values are commonly interpreted on a dry matter basis.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["dry matter percent", "DM"],
        "related_terms": ["moisture_pct", "hay_nir"],
    },

    "rfv": {
        "display_label": "Relative Feed Value",
        "source_label": "RFV",
        "dataset_family": "hay_nir",
        "group": "Forage Quality Indices",
        "units": None,
        "value_type": "index",
        "definition": "Relative feed value index used to summarize forage quality from fiber-based measures.",
        "interpretation_note": "Higher RFV generally indicates higher forage quality, but it should be interpreted with other forage metrics.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["RFV", "relative feed value"],
        "related_terms": ["adf_pct_db", "ndf_pct_db", "hay_nir"],
    },

    "rfq": {
        "display_label": "Relative Forage Quality",
        "source_label": "RFQ",
        "dataset_family": "hay_nir",
        "group": "Forage Quality Indices",
        "units": None,
        "value_type": "index",
        "definition": "Relative forage quality index used to summarize forage quality using fiber digestibility and intake-related measures.",
        "interpretation_note": "Higher RFQ generally indicates higher forage quality and may better reflect digestibility than RFV.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["RFQ", "relative forage quality"],
        "related_terms": ["ndfd48_pctndf_db", "tdn_pct_db", "hay_nir"],
    },
    "crude_protein_pct_db": {
        "display_label": "Crude Protein",
        "source_label": "Crude Protein",
        "dataset_family": "hay_nir",
        "group": "Protein & Energy",
        "units": "% dry basis",
        "value_type": "percent",
        "definition": "Estimated crude protein concentration of the forage sample on a dry matter basis.",
        "interpretation_note": "Higher crude protein generally indicates greater nitrogen and protein availability in forage.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["crude protein", "CP"],
        "related_terms": ["tdn_pct_db", "nel_pct_db", "hay_nir"],
    },

    "adf_pct_db": {
        "display_label": "Acid Detergent Fiber (ADF)",
        "source_label": "ADF",
        "dataset_family": "hay_nir",
        "group": "Protein & Energy",
        "units": "% dry basis",
        "value_type": "percent",
        "definition": "Acid detergent fiber concentration of the forage sample on a dry matter basis.",
        "interpretation_note": "Higher ADF generally indicates lower digestibility and reduced forage energy availability.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["ADF", "acid detergent fiber"],
        "related_terms": ["ndf_pct_db", "tdn_pct_db", "rfv"],
    },

    "ndf_pct_db": {
        "display_label": "Neutral Detergent Fiber (NDF)",
        "source_label": "NDF",
        "dataset_family": "hay_nir",
        "group": "Protein & Energy",
        "units": "% dry basis",
        "value_type": "percent",
        "definition": "Neutral detergent fiber concentration of the forage sample on a dry matter basis.",
        "interpretation_note": "Higher NDF generally indicates lower forage intake potential.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["NDF", "neutral detergent fiber"],
        "related_terms": ["adf_pct_db", "rfv", "rfq"],
    },

    "tdn_pct_db": {
        "display_label": "Total Digestible Nutrients (TDN)",
        "source_label": "TDN",
        "dataset_family": "hay_nir",
        "group": "Protein & Energy",
        "units": "% dry basis",
        "value_type": "percent",
        "definition": "Estimated total digestible nutrient concentration of the forage sample.",
        "interpretation_note": "Higher TDN generally indicates greater available forage energy.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["TDN", "total digestible nutrients"],
        "related_terms": ["nel_pct_db", "nem_pct_db", "neg_pct_db"],
    },

    "nel_pct_db": {
        "display_label": "Net Energy for Lactation (NEL)",
        "source_label": "NEL",
        "dataset_family": "hay_nir",
        "group": "Protein & Energy",
        "units": "Mcal/lb",
        "value_type": "energy",
        "definition": "Estimated net energy available for lactation from the forage sample.",
        "interpretation_note": "Higher NEL values generally indicate greater forage energy available for milk production.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["NEL", "net energy lactation"],
        "related_terms": ["tdn_pct_db", "nem_pct_db", "neg_pct_db"],
    },

    "nem_pct_db": {
        "display_label": "Net Energy for Maintenance (NEM)",
        "source_label": "NEM",
        "dataset_family": "hay_nir",
        "group": "Protein & Energy",
        "units": "Mcal/lb",
        "value_type": "energy",
        "definition": "Estimated net energy available for animal maintenance from the forage sample.",
        "interpretation_note": "Higher NEM values generally indicate greater maintenance energy availability.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["NEM", "net energy maintenance"],
        "related_terms": ["tdn_pct_db", "nel_pct_db", "neg_pct_db"],
    },

    "neg_pct_db": {
        "display_label": "Net Energy for Gain (NEG)",
        "source_label": "NEG",
        "dataset_family": "hay_nir",
        "group": "Protein & Energy",
        "units": "Mcal/lb",
        "value_type": "energy",
        "definition": "Estimated net energy available for animal weight gain from the forage sample.",
        "interpretation_note": "Higher NEG values generally indicate greater forage energy available for growth and gain.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["NEG", "net energy gain"],
        "related_terms": ["tdn_pct_db", "nel_pct_db", "nem_pct_db"],
    },
    "ndfd48_pctndf_db": {
        "display_label": "NDF Digestibility at 48h (NDFD48)",
        "source_label": "NDFD48",
        "dataset_family": "hay_nir",
        "group": "Digestibility & Fiber",
        "units": "% NDF",
        "value_type": "percent",
        "definition": "Estimated neutral detergent fiber digestibility after 48 hours.",
        "interpretation_note": "Higher NDF digestibility generally indicates greater forage digestibility and improved intake potential.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["NDFD48", "NDF digestibility"],
        "related_terms": ["ndf_pct_db", "rfq", "ivtdmd48_pctndf_db"],
    },

    "ivtdmd48_pctndf_db": {
        "display_label": "IVTDMD48",
        "source_label": "IVTDMD48",
        "dataset_family": "hay_nir",
        "group": "Digestibility & Fiber",
        "units": "% dry basis",
        "value_type": "percent",
        "definition": "Estimated in vitro true dry matter digestibility after 48 hours.",
        "interpretation_note": "Higher IVTDMD values generally indicate greater forage digestibility and energy availability.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["IVTDMD48", "in vitro digestibility"],
        "related_terms": ["ndfd48_pctndf_db", "tdn_pct_db", "rfq"],
    },

    "lignin_pct_db": {
        "display_label": "Lignin",
        "source_label": "Lignin",
        "dataset_family": "hay_nir",
        "group": "Digestibility & Fiber",
        "units": "% dry basis",
        "value_type": "percent",
        "definition": "Estimated lignin concentration of the forage sample.",
        "interpretation_note": "Higher lignin generally reduces forage digestibility because lignin is resistant to microbial breakdown.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["lignin"],
        "related_terms": ["adf_pct_db", "ndf_pct_db", "ivtdmd48_pctndf_db"],
    },

    "fat_pct_db": {
        "display_label": "Fat",
        "source_label": "Fat",
        "dataset_family": "hay_nir",
        "group": "Carbohydrates & Fat",
        "units": "% dry basis",
        "value_type": "percent",
        "definition": "Estimated crude fat concentration of the forage sample.",
        "interpretation_note": "Fat contributes concentrated energy to forage quality.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["ether extract", "fat"],
        "related_terms": ["tdn_pct_db", "nel_pct_db"],
    },

    "nfc_pct_db": {
        "display_label": "Non-Fiber Carbohydrates (NFC)",
        "source_label": "NFC",
        "dataset_family": "hay_nir",
        "group": "Carbohydrates & Fat",
        "units": "% dry basis",
        "value_type": "percent",
        "definition": "Estimated non-fiber carbohydrate concentration of the forage sample.",
        "interpretation_note": "NFC represents rapidly available carbohydrates including sugars and starches.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["NFC", "non-fiber carbohydrates"],
        "related_terms": ["starch_pct_db", "esc_pct_db", "wsc_pct_db"],
    },

    "starch_pct_db": {
        "display_label": "Starch",
        "source_label": "Starch",
        "dataset_family": "hay_nir",
        "group": "Carbohydrates & Fat",
        "units": "% dry basis",
        "value_type": "percent",
        "definition": "Estimated starch concentration of the forage sample.",
        "interpretation_note": "Higher starch generally indicates greater rapidly available energy.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["starch"],
        "related_terms": ["nfc_pct_db", "esc_pct_db", "wsc_pct_db"],
    },

    "esc_pct_db": {
        "display_label": "Ethanol Soluble Carbohydrates (ESC)",
        "source_label": "ESC",
        "dataset_family": "hay_nir",
        "group": "Carbohydrates & Fat",
        "units": "% dry basis",
        "value_type": "percent",
        "definition": "Estimated ethanol soluble carbohydrate concentration of the forage sample.",
        "interpretation_note": "ESC represents readily fermentable sugars in forage.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["ESC", "ethanol soluble carbohydrates"],
        "related_terms": ["wsc_pct_db", "nfc_pct_db", "starch_pct_db"],
    },

    "wsc_pct_db": {
        "display_label": "Water Soluble Carbohydrates (WSC)",
        "source_label": "WSC",
        "dataset_family": "hay_nir",
        "group": "Carbohydrates & Fat",
        "units": "% dry basis",
        "value_type": "percent",
        "definition": "Estimated water soluble carbohydrate concentration of the forage sample.",
        "interpretation_note": "WSC includes sugars that are rapidly available to rumen microbes.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["WSC", "water soluble carbohydrates"],
        "related_terms": ["esc_pct_db", "nfc_pct_db", "starch_pct_db"],
    },

    "fructan_pct_db": {
        "display_label": "Fructan",
        "source_label": "Fructan",
        "dataset_family": "hay_nir",
        "group": "Carbohydrates & Fat",
        "units": "% dry basis",
        "value_type": "percent",
        "definition": "Estimated fructan concentration of the forage sample.",
        "interpretation_note": "Fructans are storage carbohydrates commonly found in cool-season grasses.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["fructan"],
        "related_terms": ["wsc_pct_db", "esc_pct_db", "nfc_pct_db"],
    },
    "ash_pct_db": {
        "display_label": "Ash",
        "source_label": "Ash",
        "dataset_family": "hay_nir",
        "group": "Minerals & Ash",
        "units": "% dry basis",
        "value_type": "percent",
        "definition": "Estimated total mineral residue remaining after complete combustion of the forage sample.",
        "interpretation_note": "Ash represents total mineral content and may increase with soil contamination or dust.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["ash", "total ash"],
        "related_terms": ["ca_pct_db", "p_pct_db", "k_pct_db", "mg_pct_db"],
    },

    "ca_pct_db": {
        "display_label": "Calcium",
        "source_label": "Ca",
        "dataset_family": "hay_nir",
        "group": "Minerals & Ash",
        "units": "% dry basis",
        "value_type": "percent",
        "definition": "Estimated calcium concentration of the forage sample.",
        "interpretation_note": "Calcium is an essential macromineral important for plant and animal health.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["Ca", "calcium"],
        "related_terms": ["p_pct_db", "mg_pct_db", "ash_pct_db"],
    },

    "p_pct_db": {
        "display_label": "Phosphorus",
        "source_label": "P",
        "dataset_family": "hay_nir",
        "group": "Minerals & Ash",
        "units": "% dry basis",
        "value_type": "percent",
        "definition": "Estimated phosphorus concentration of the forage sample.",
        "interpretation_note": "Phosphorus is an essential nutrient involved in energy transfer and metabolism.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["P", "phosphorus"],
        "related_terms": ["ca_pct_db", "k_pct_db", "ash_pct_db"],
    },

    "k_pct_db": {
        "display_label": "Potassium",
        "source_label": "K",
        "dataset_family": "hay_nir",
        "group": "Minerals & Ash",
        "units": "% dry basis",
        "value_type": "percent",
        "definition": "Estimated potassium concentration of the forage sample.",
        "interpretation_note": "Potassium is an important plant nutrient involved in water regulation and metabolic processes.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["K", "potassium"],
        "related_terms": ["ca_pct_db", "mg_pct_db", "ash_pct_db"],
    },

    "mg_pct_db": {
        "display_label": "Magnesium",
        "source_label": "Mg",
        "dataset_family": "hay_nir",
        "group": "Minerals & Ash",
        "units": "% dry basis",
        "value_type": "percent",
        "definition": "Estimated magnesium concentration of the forage sample.",
        "interpretation_note": "Magnesium is an essential nutrient involved in chlorophyll formation and enzyme activity.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["Mg", "magnesium"],
        "related_terms": ["ca_pct_db", "k_pct_db", "ash_pct_db"],
    },
    "ash_pct_db": {
        "display_label": "Ash",
        "source_label": "Ash",
        "dataset_family": "hay_nir",
        "group": "Minerals & Ash",
        "units": "% dry basis",
        "value_type": "percent",
        "definition": "Estimated total mineral residue remaining after complete combustion of the forage sample.",
        "interpretation_note": "Ash represents total mineral content and may increase with soil contamination or dust.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["ash", "total ash"],
        "related_terms": ["ca_pct_db", "p_pct_db", "k_pct_db", "mg_pct_db"],
    },

    "ca_pct_db": {
        "display_label": "Calcium",
        "source_label": "Ca",
        "dataset_family": "hay_nir",
        "group": "Minerals & Ash",
        "units": "% dry basis",
        "value_type": "percent",
        "definition": "Estimated calcium concentration of the forage sample.",
        "interpretation_note": "Calcium is an essential macromineral important for plant and animal health.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["Ca", "calcium"],
        "related_terms": ["p_pct_db", "mg_pct_db", "ash_pct_db"],
    },

    "p_pct_db": {
        "display_label": "Phosphorus",
        "source_label": "P",
        "dataset_family": "hay_nir",
        "group": "Minerals & Ash",
        "units": "% dry basis",
        "value_type": "percent",
        "definition": "Estimated phosphorus concentration of the forage sample.",
        "interpretation_note": "Phosphorus is an essential nutrient involved in energy transfer and metabolism.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["P", "phosphorus"],
        "related_terms": ["ca_pct_db", "k_pct_db", "ash_pct_db"],
    },

    "k_pct_db": {
        "display_label": "Potassium",
        "source_label": "K",
        "dataset_family": "hay_nir",
        "group": "Minerals & Ash",
        "units": "% dry basis",
        "value_type": "percent",
        "definition": "Estimated potassium concentration of the forage sample.",
        "interpretation_note": "Potassium is an important plant nutrient involved in water regulation and metabolic processes.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["K", "potassium"],
        "related_terms": ["ca_pct_db", "mg_pct_db", "ash_pct_db"],
    },

    "mg_pct_db": {
        "display_label": "Magnesium",
        "source_label": "Mg",
        "dataset_family": "hay_nir",
        "group": "Minerals & Ash",
        "units": "% dry basis",
        "value_type": "percent",
        "definition": "Estimated magnesium concentration of the forage sample.",
        "interpretation_note": "Magnesium is an essential nutrient involved in chlorophyll formation and enzyme activity.",
        "source_reference_group": "Ward NIR Forage Analysis",
        "aliases": ["Mg", "magnesium"],
        "related_terms": ["ca_pct_db", "k_pct_db", "ash_pct_db"],
    },
    "soil_ph_1_1": {
        "display_label": "Soil pH (1:1)",
        "source_label": "1:1 Soil pH",
        "dataset_family": "soil_chemistry",
        "group": "pH, Salinity & Lime",
        "units": None,
        "value_type": "index",
        "definition": "Soil pH measured using a 1:1 soil-to-water method.",
        "interpretation_note": "Soil pH affects nutrient availability, microbial activity, and crop suitability.",
        "source_reference_group": "Ward Soil Chemistry Report",
        "aliases": ["1_1_soil_ph", "soil_ph", "soil pH", "1:1 soil pH"],
        "related_terms": ["wdrf_buffer_ph", "excess_lime"],
    },

    "wdrf_buffer_ph": {
        "display_label": "WDRF Buffer pH",
        "source_label": "WDRF Buffer pH",
        "dataset_family": "soil_chemistry",
        "group": "pH, Salinity & Lime",
        "units": None,
        "value_type": "index",
        "definition": "Buffer pH used to estimate lime requirement and soil buffering capacity.",
        "interpretation_note": "Buffer pH helps interpret how strongly the soil resists pH change.",
        "source_reference_group": "Ward Soil Chemistry Report",
        "aliases": ["buffer pH", "WDRF buffer"],
        "related_terms": ["soil_ph_1_1", "excess_lime"],
    },

    "ec_1_1": {
        "display_label": "Electrical Conductivity (1:1)",
        "source_label": "1:1 Soluble Salts",
        "dataset_family": "soil_chemistry",
        "group": "pH, Salinity & Lime",
        "units": "mmho/cm",
        "value_type": "concentration",
        "definition": "Electrical conductivity or soluble salts measured using a 1:1 soil-water extract.",
        "interpretation_note": "Higher EC indicates greater soluble salt concentration and potential salinity stress.",
        "source_reference_group": "Ward Soil Chemistry Report",
        "aliases": ["1_1_s_salts_mmho_cm", "soluble salts", "EC", "electrical conductivity"],
        "related_terms": ["soil_ph_1_1", "sodium_ppm_na"],
    },

    "excess_lime": {
        "display_label": "Excess Lime",
        "source_label": "Excess Lime",
        "dataset_family": "soil_chemistry",
        "group": "pH, Salinity & Lime",
        "units": None,
        "value_type": "descriptor",
        "definition": "Indicator of excess calcium carbonate or lime in the soil.",
        "interpretation_note": "Excess lime can affect nutrient availability, especially phosphorus and micronutrients.",
        "source_reference_group": "Ward Soil Chemistry Report",
        "aliases": ["lime", "calcium carbonate", "excess calcium carbonate"],
        "related_terms": ["soil_ph_1_1", "calcium_ppm_ca"],
    },

    "cec_meq_100g": {
        "display_label": "Cation Exchange Capacity (CEC)",
        "source_label": "CEC",
        "dataset_family": "soil_chemistry",
        "group": "CEC & Base Saturation",
        "units": "meq/100g",
        "value_type": "concentration",
        "definition": "Cation exchange capacity, representing the soil's ability to hold exchangeable nutrient cations.",
        "interpretation_note": "Higher CEC generally indicates greater capacity to retain cation nutrients such as calcium, magnesium, potassium, and sodium.",
        "source_reference_group": "Ward Soil Chemistry Report",
        "aliases": ["cec_sum_of_cations_me_100g", "sum_of_cations_meq_100g", "CEC"],
        "related_terms": ["pctca_sat", "pctmg_sat", "pctk_sat", "pctna_sat"],
    },
    "organic_matter_loi_pct": {
        "display_label": "Organic Matter",
        "source_label": "Organic Matter LOI",
        "dataset_family": "soil_chemistry",
        "group": "Organic Matter & Macronutrients",
        "units": "%",
        "value_type": "percent",
        "definition": "Soil organic matter estimated by loss-on-ignition.",
        "interpretation_note": "Higher organic matter generally improves nutrient retention, water holding, soil structure, and microbial habitat.",
        "source_reference_group": "Ward Soil Chemistry Report",
        "aliases": ["organic matter", "OM", "LOI organic matter"],
        "related_terms": ["organic_c_h2o_ppm", "microbially_active_carbon_pctma"],
    },

    "olsen_p_ppm_p": {
        "display_label": "Olsen Phosphorus",
        "source_label": "Olsen P",
        "dataset_family": "soil_chemistry",
        "group": "Organic Matter & Macronutrients",
        "units": "ppm P",
        "value_type": "concentration",
        "definition": "Plant-available phosphorus measured using the Olsen extraction method.",
        "interpretation_note": "Olsen phosphorus is commonly used for calcareous or higher-pH soils.",
        "source_reference_group": "Ward Soil Chemistry Report",
        "aliases": ["Olsen P", "phosphorus", "available phosphorus"],
        "related_terms": ["p2o5_rec", "soil_ph_1_1", "excess_lime"],
    },

    "potassium_ppm_k": {
        "display_label": "Potassium",
        "source_label": "Potassium",
        "dataset_family": "soil_chemistry",
        "group": "Organic Matter & Macronutrients",
        "units": "ppm K",
        "value_type": "concentration",
        "definition": "Soil potassium concentration reported as ppm K.",
        "interpretation_note": "Potassium is an essential plant macronutrient involved in water regulation and stress response.",
        "source_reference_group": "Ward Soil Chemistry Report",
        "aliases": ["K", "potassium ppm", "ppm K"],
        "related_terms": ["k2o_rec", "pctk_sat"],
    },

    "sulfate_s_ppm_s": {
        "display_label": "Sulfate-S",
        "source_label": "Sulfate-S",
        "dataset_family": "soil_chemistry",
        "group": "Organic Matter & Macronutrients",
        "units": "ppm S",
        "value_type": "concentration",
        "definition": "Soil sulfate sulfur concentration reported as ppm S.",
        "interpretation_note": "Sulfate-S is the primary plant-available form of sulfur in soil tests.",
        "source_reference_group": "Ward Soil Chemistry Report",
        "aliases": ["sulfate sulfur", "sulfate-S", "sulfur ppm"],
        "related_terms": ["sulfur_rec"],
    },

    "nitrate_n_ppm": {
        "display_label": "Nitrate-N",
        "source_label": "Nitrate-N",
        "dataset_family": "soil_chemistry",
        "group": "Organic Matter & Macronutrients",
        "units": "ppm N",
        "value_type": "concentration",
        "definition": "Soil nitrate nitrogen concentration reported as ppm N.",
        "interpretation_note": "Nitrate-N is a readily plant-available form of nitrogen and can change rapidly with irrigation, rainfall, and biological activity.",
        "source_reference_group": "Ward Soil Chemistry Report",
        "aliases": ["nitrate nitrogen", "NO3-N", "nitrate-N"],
        "related_terms": ["h2o_no3_n", "nitrogen_rec"],
    },
    "calcium_ppm_ca": {
        "display_label": "Calcium",
        "source_label": "Calcium",
        "dataset_family": "soil_chemistry",
        "group": "CEC & Base Saturation",
        "units": "ppm Ca",
        "value_type": "concentration",
        "definition": "Soil calcium concentration reported as ppm Ca.",
        "interpretation_note": "Calcium is an exchangeable base cation important for soil structure and plant nutrition.",
        "source_reference_group": "Ward Soil Chemistry Report",
        "aliases": ["Ca", "calcium ppm", "ppm Ca"],
        "related_terms": ["pctca_sat", "cec_meq_100g", "excess_lime"],
    },

    "magnesium_ppm_mg": {
        "display_label": "Magnesium",
        "source_label": "Magnesium",
        "dataset_family": "soil_chemistry",
        "group": "CEC & Base Saturation",
        "units": "ppm Mg",
        "value_type": "concentration",
        "definition": "Soil magnesium concentration reported as ppm Mg.",
        "interpretation_note": "Magnesium is an exchangeable base cation and an essential plant nutrient.",
        "source_reference_group": "Ward Soil Chemistry Report",
        "aliases": ["Mg", "magnesium ppm", "ppm Mg"],
        "related_terms": ["pctmg_sat", "cec_meq_100g"],
    },

    "sodium_ppm_na": {
        "display_label": "Sodium",
        "source_label": "Sodium",
        "dataset_family": "soil_chemistry",
        "group": "CEC & Base Saturation",
        "units": "ppm Na",
        "value_type": "concentration",
        "definition": "Soil sodium concentration reported as ppm Na.",
        "interpretation_note": "Elevated sodium can affect soil structure, infiltration, and salinity/sodicity risk.",
        "source_reference_group": "Ward Soil Chemistry Report",
        "aliases": ["Na", "sodium ppm", "ppm Na"],
        "related_terms": ["pctna_sat", "ec_1_1"],
    },

    "pcth_sat": {
        "display_label": "Hydrogen Saturation",
        "source_label": "% H Saturation",
        "dataset_family": "soil_chemistry",
        "group": "CEC & Base Saturation",
        "units": "%",
        "value_type": "percent",
        "definition": "Percentage of the soil cation exchange capacity occupied by hydrogen.",
        "interpretation_note": "Higher hydrogen saturation is commonly associated with more acidic soil conditions.",
        "source_reference_group": "Ward Soil Chemistry Report",
        "aliases": ["% H sat", "hydrogen saturation"],
        "related_terms": ["soil_ph_1_1", "cec_meq_100g"],
    },

    "pctk_sat": {
        "display_label": "Potassium Saturation",
        "source_label": "% K Saturation",
        "dataset_family": "soil_chemistry",
        "group": "CEC & Base Saturation",
        "units": "%",
        "value_type": "percent",
        "definition": "Percentage of the soil cation exchange capacity occupied by potassium.",
        "interpretation_note": "Potassium saturation helps interpret potassium status relative to overall exchange capacity.",
        "source_reference_group": "Ward Soil Chemistry Report",
        "aliases": ["% K sat", "potassium saturation"],
        "related_terms": ["potassium_ppm_k", "cec_meq_100g"],
    },

    "pctca_sat": {
        "display_label": "Calcium Saturation",
        "source_label": "% Ca Saturation",
        "dataset_family": "soil_chemistry",
        "group": "CEC & Base Saturation",
        "units": "%",
        "value_type": "percent",
        "definition": "Percentage of the soil cation exchange capacity occupied by calcium.",
        "interpretation_note": "Calcium saturation helps interpret calcium status relative to overall exchange capacity.",
        "source_reference_group": "Ward Soil Chemistry Report",
        "aliases": ["% Ca sat", "calcium saturation"],
        "related_terms": ["calcium_ppm_ca", "cec_meq_100g"],
    },

    "pctmg_sat": {
        "display_label": "Magnesium Saturation",
        "source_label": "% Mg Saturation",
        "dataset_family": "soil_chemistry",
        "group": "CEC & Base Saturation",
        "units": "%",
        "value_type": "percent",
        "definition": "Percentage of the soil cation exchange capacity occupied by magnesium.",
        "interpretation_note": "Magnesium saturation helps interpret magnesium status relative to overall exchange capacity.",
        "source_reference_group": "Ward Soil Chemistry Report",
        "aliases": ["% Mg sat", "magnesium saturation"],
        "related_terms": ["magnesium_ppm_mg", "cec_meq_100g"],
    },

    "pctna_sat": {
        "display_label": "Sodium Saturation",
        "source_label": "% Na Saturation",
        "dataset_family": "soil_chemistry",
        "group": "CEC & Base Saturation",
        "units": "%",
        "value_type": "percent",
        "definition": "Percentage of the soil cation exchange capacity occupied by sodium.",
        "interpretation_note": "Higher sodium saturation may indicate sodicity risk and potential soil structure problems.",
        "source_reference_group": "Ward Soil Chemistry Report",
        "aliases": ["% Na sat", "sodium saturation"],
        "related_terms": ["sodium_ppm_na", "ec_1_1", "cec_meq_100g"],
    },
    "zinc_ppm_zn": {
        "display_label": "Zinc",
        "source_label": "Zinc",
        "dataset_family": "soil_chemistry",
        "group": "Micronutrients",
        "units": "ppm Zn",
        "value_type": "concentration",
        "definition": "Soil zinc concentration reported as ppm Zn.",
        "interpretation_note": "Zinc is an essential micronutrient involved in enzyme activity and plant growth.",
        "source_reference_group": "Ward Soil Chemistry Report",
        "aliases": ["Zn", "zinc ppm", "ppm Zn"],
        "related_terms": ["zinc_rec", "soil_ph_1_1"],
    },

    "iron_ppm_fe": {
        "display_label": "Iron",
        "source_label": "Iron",
        "dataset_family": "soil_chemistry",
        "group": "Micronutrients",
        "units": "ppm Fe",
        "value_type": "concentration",
        "definition": "Soil iron concentration reported as ppm Fe.",
        "interpretation_note": "Iron availability is strongly influenced by soil pH and aeration.",
        "source_reference_group": "Ward Soil Chemistry Report",
        "aliases": ["Fe", "iron ppm", "ppm Fe"],
        "related_terms": ["iron_rec", "soil_ph_1_1"],
    },

    "manganese_ppm_mn": {
        "display_label": "Manganese",
        "source_label": "Manganese",
        "dataset_family": "soil_chemistry",
        "group": "Micronutrients",
        "units": "ppm Mn",
        "value_type": "concentration",
        "definition": "Soil manganese concentration reported as ppm Mn.",
        "interpretation_note": "Manganese availability is affected by soil pH, drainage, and oxidation conditions.",
        "source_reference_group": "Ward Soil Chemistry Report",
        "aliases": ["Mn", "manganese ppm", "ppm Mn"],
        "related_terms": ["manganese_rec", "soil_ph_1_1"],
    },

    "copper_ppm_cu": {
        "display_label": "Copper",
        "source_label": "Copper",
        "dataset_family": "soil_chemistry",
        "group": "Micronutrients",
        "units": "ppm Cu",
        "value_type": "concentration",
        "definition": "Soil copper concentration reported as ppm Cu.",
        "interpretation_note": "Copper is an essential micronutrient involved in enzyme systems and plant metabolism.",
        "source_reference_group": "Ward Soil Chemistry Report",
        "aliases": ["Cu", "copper ppm", "ppm Cu"],
        "related_terms": ["copper_rec", "organic_matter_loi_pct"],
    },

    "boron_ppm_b": {
        "display_label": "Boron",
        "source_label": "Boron",
        "dataset_family": "soil_chemistry",
        "group": "Micronutrients",
        "units": "ppm B",
        "value_type": "concentration",
        "definition": "Soil boron concentration reported as ppm B.",
        "interpretation_note": "Boron is required in small amounts but can become deficient or toxic depending on concentration and soil conditions.",
        "source_reference_group": "Ward Soil Chemistry Report",
        "aliases": ["B", "boron ppm", "ppm B"],
        "related_terms": ["boron_rec", "soil_ph_1_1"],
    },
    "h2o_no3_n": {
        "display_label": "Water Extractable Nitrate-N",
        "source_label": "H2O NO3-N",
        "dataset_family": "soil_chemistry",
        "group": "Soil Health Indicators",
        "units": "ppm N",
        "value_type": "concentration",
        "definition": "Water-extractable nitrate nitrogen concentration.",
        "interpretation_note": "Represents a readily soluble form of nitrogen that can change rapidly with moisture, irrigation, and biological activity.",
        "source_reference_group": "Ward Soil Health Report",
        "aliases": ["H2O NO3-N", "water nitrate", "water extractable nitrate"],
        "related_terms": ["nitrate_n_ppm", "nitrogen_rec"],
    },

    "h2o_nh4_n": {
        "display_label": "Water Extractable Ammonium-N",
        "source_label": "H2O NH4-N",
        "dataset_family": "soil_chemistry",
        "group": "Soil Health Indicators",
        "units": "ppm N",
        "value_type": "concentration",
        "definition": "Water-extractable ammonium nitrogen concentration.",
        "interpretation_note": "Represents a soluble ammonium nitrogen pool that can reflect recent mineralization or fertilizer effects.",
        "source_reference_group": "Ward Soil Health Report",
        "aliases": ["H2O NH4-N", "water ammonium", "water extractable ammonium"],
        "related_terms": ["h2o_no3_n", "total_n_h2o_ppm_n"],
    },

    "organic_c_h2o_ppm": {
        "display_label": "Water Extractable Organic Carbon",
        "source_label": "Organic C H2O",
        "dataset_family": "soil_chemistry",
        "group": "Soil Health Indicators",
        "units": "ppm C",
        "value_type": "concentration",
        "definition": "Water-extractable organic carbon concentration.",
        "interpretation_note": "This pool can reflect soluble carbon available for microbial activity.",
        "source_reference_group": "Ward Soil Health Report",
        "aliases": ["organic carbon H2O", "water extractable organic carbon", "WEOC"],
        "related_terms": ["organic_matter_loi_pct", "microbially_active_carbon_pctma"],
    },

    "organic_n_h2o_ppm": {
        "display_label": "Water Extractable Organic Nitrogen",
        "source_label": "Organic N H2O",
        "dataset_family": "soil_chemistry",
        "group": "Soil Health Indicators",
        "units": "ppm N",
        "value_type": "concentration",
        "definition": "Water-extractable organic nitrogen concentration.",
        "interpretation_note": "This pool can reflect soluble organic nitrogen available for microbial processing.",
        "source_reference_group": "Ward Soil Health Report",
        "aliases": ["organic nitrogen H2O", "water extractable organic nitrogen", "WEON"],
        "related_terms": ["organic_c_h2o_ppm", "organic_c_n_h2o"],
    },

    "organic_c_n_h2o": {
        "display_label": "Water Extractable Organic C:N Ratio",
        "source_label": "Organic C:N H2O",
        "dataset_family": "soil_chemistry",
        "group": "Soil Health Indicators",
        "units": None,
        "value_type": "ratio",
        "definition": "Ratio of water-extractable organic carbon to water-extractable organic nitrogen.",
        "interpretation_note": "Can help interpret the balance between soluble carbon and nitrogen pools available for microbial activity.",
        "source_reference_group": "Ward Soil Health Report",
        "aliases": ["organic C:N H2O", "water extractable organic C:N"],
        "related_terms": ["organic_c_h2o_ppm", "organic_n_h2o_ppm"],
    },

    "co2_soil_respiration": {
        "display_label": "CO₂ Soil Respiration",
        "source_label": "CO2 Soil Respiration",
        "dataset_family": "soil_chemistry",
        "group": "Soil Health Indicators",
        "units": None,
        "value_type": "index",
        "definition": "Laboratory soil respiration indicator based on carbon dioxide release.",
        "interpretation_note": "Higher values generally indicate greater microbial respiration activity under the test conditions.",
        "source_reference_group": "Ward Soil Health Report",
        "aliases": ["CO2 respiration", "soil respiration", "CO₂ respiration"],
        "related_terms": ["microbially_active_carbon_pctma", "organic_matter_loi_pct"],
    },

    "water_stable_aggregates_mod": {
        "display_label": "Water Stable Aggregates",
        "source_label": "Water Stable Aggregates",
        "dataset_family": "soil_chemistry",
        "group": "Soil Health Indicators",
        "units": "%",
        "value_type": "percent",
        "definition": "Modified water-stable aggregate measurement.",
        "interpretation_note": "Higher values generally indicate better soil aggregation and structural stability.",
        "source_reference_group": "Ward Soil Health Report",
        "aliases": ["water stable aggregates", "aggregate stability"],
        "related_terms": ["organic_matter_loi_pct", "soil_health_score"],
    },

    "total_n_h2o_ppm_n": {
        "display_label": "Water Extractable Total Nitrogen",
        "source_label": "Total N H2O",
        "dataset_family": "soil_chemistry",
        "group": "Soil Health Indicators",
        "units": "ppm N",
        "value_type": "concentration",
        "definition": "Total water-extractable nitrogen concentration.",
        "interpretation_note": "Represents the combined water-extractable nitrogen pool measured by the lab.",
        "source_reference_group": "Ward Soil Health Report",
        "aliases": ["total nitrogen H2O", "water extractable total nitrogen"],
        "related_terms": ["h2o_no3_n", "h2o_nh4_n", "organic_n_h2o_ppm"],
    },

    "soil_health_score": {
        "display_label": "Soil Health Score",
        "source_label": "Soil Health Score",
        "dataset_family": "soil_chemistry",
        "group": "Soil Health Indicators",
        "units": None,
        "value_type": "index",
        "definition": "Composite soil health score reported by the laboratory.",
        "interpretation_note": "Useful as a summary indicator, but individual component variables should be reviewed to understand causes of change.",
        "source_reference_group": "Ward Soil Health Report",
        "aliases": ["soil health score"],
        "related_terms": ["co2_soil_respiration", "water_stable_aggregates_mod", "microbially_active_carbon_pctma"],
    },

    "microbially_active_carbon_pctma": {
        "display_label": "Microbially Active Carbon",
        "source_label": "Microbially Active Carbon",
        "dataset_family": "soil_chemistry",
        "group": "Soil Health Indicators",
        "units": "%",
        "value_type": "percent",
        "definition": "Laboratory-reported microbially active carbon indicator.",
        "interpretation_note": "May indicate the portion of carbon more closely associated with microbial activity.",
        "source_reference_group": "Ward Soil Health Report",
        "aliases": ["microbially active carbon", "active carbon"],
        "related_terms": ["organic_c_h2o_ppm", "co2_soil_respiration"],
    },

    "organic_nitrogen_release_ppm_n": {
        "display_label": "Organic Nitrogen Release",
        "source_label": "Organic Nitrogen Release",
        "dataset_family": "soil_chemistry",
        "group": "Soil Health Indicators",
        "units": "ppm N",
        "value_type": "concentration",
        "definition": "Laboratory estimate of nitrogen released from organic nitrogen pools.",
        "interpretation_note": "Can help evaluate nitrogen mineralization potential from organic matter.",
        "source_reference_group": "Ward Soil Health Report",
        "aliases": ["organic nitrogen release", "organic N release"],
        "related_terms": ["organic_nitrogen_reserve_ppm_n", "organic_matter_loi_pct"],
    },

    "organic_nitrogen_reserve_ppm_n": {
        "display_label": "Organic Nitrogen Reserve",
        "source_label": "Organic Nitrogen Reserve",
        "dataset_family": "soil_chemistry",
        "group": "Soil Health Indicators",
        "units": "ppm N",
        "value_type": "concentration",
        "definition": "Laboratory estimate of organic nitrogen reserve in the soil.",
        "interpretation_note": "Can help evaluate longer-term nitrogen supply potential from organic matter.",
        "source_reference_group": "Ward Soil Health Report",
        "aliases": ["organic nitrogen reserve", "organic N reserve"],
        "related_terms": ["organic_nitrogen_release_ppm_n", "organic_matter_loi_pct"],
    },

}

def get_lab_variable_metadata(key: str) -> dict:
    return LAB_VARIABLE_METADATA.get(key, {})

def get_display_label(key: str) -> str:
    return LAB_VARIABLE_METADATA.get(key, {}).get("display_label", key)

def get_units(key: str) -> str | None:
    return LAB_VARIABLE_METADATA.get(key, {}).get("units")
