"""
Central metadata registry for lab variables used in the Biochar Fruita CSU dashboard.

This file should describe existing standardized column names.

Do not rename source columns here.
"""

from __future__ import annotations

LAB_VARIABLE_METADATA = {

    'actinomycetes_biomass': {'display_label': 'Actinomycetes Biomass',
                           'source_label': 'Actinomycetes',
                           'dataset_family': 'soil_biology_plfa',
                           'group': 'Functional Group Biomass',
                           'units': 'ng/g',
                           'value_type': 'biomass',
                           'definition': 'Estimated biomass of actinomycetes based on PLFA '
                                         'biomarkers.',
                           'interpretation_note': 'Actinomycetes are bacteria often associated '
                                                  'with decomposition of complex organic '
                                                  'materials.',
                           'source_reference_group': 'Ward PLFA Biological Report',
                           'aliases': ['actinomycete biomass', 'actinomycetes'],
                           'related_terms': ['bacteria',
                                             'decomposition',
                                             'plfa',
                                             'microbial_biomass']},
 'actinomycetes_pct': {'display_label': 'Actinomycetes (%)',
                       'source_label': 'Actinomycetes %',
                       'dataset_family': 'soil_biology_plfa',
                       'group': 'Relative Abundance',
                       'units': '%',
                       'value_type': 'percent',
                       'definition': 'Relative abundance of actinomycetes as a percentage of total '
                                     'microbial biomass.',
                       'interpretation_note': 'This is a relative abundance measure rather than an '
                                              'absolute biomass value.',
                       'source_reference_group': 'Ward PLFA Biological Report',
                       'aliases': ['actinomycetes percent', 'actinomycete percent'],
                       'related_terms': ['actinomycetes_biomass', 'bacteria', 'plfa']},
 'arbuscular_mycorrhizal_biomass': {'display_label': 'Arbuscular Mycorrhizal Fungi Biomass',
                                    'source_label': 'Arbuscular Mycorrhizal',
                                    'dataset_family': 'soil_biology_plfa',
                                    'group': 'Functional Group Biomass',
                                    'units': 'ng/g',
                                    'value_type': 'biomass',
                                    'definition': 'Estimated biomass of arbuscular mycorrhizal '
                                                  'fungi based on PLFA biomarkers.',
                                    'interpretation_note': 'Arbuscular mycorrhizal fungi are '
                                                           'plant-associated fungi involved in '
                                                           'nutrient and water uptake '
                                                           'relationships.',
                                    'source_reference_group': 'Ward PLFA Biological Report',
                                    'aliases': ['AMF biomass',
                                                'arbuscular mycorrhizal biomass',
                                                'mycorrhizal fungi biomass'],
                                    'related_terms': ['fungi',
                                                      'mycorrhizae',
                                                      'plfa',
                                                      'microbial_biomass']},
 'arbuscular_mycorrhizal_pct': {'display_label': 'Arbuscular Mycorrhizal Fungi (%)',
                                'source_label': 'Arbuscular Mycorrhizal %',
                                'dataset_family': 'soil_biology_plfa',
                                'group': 'Relative Abundance',
                                'units': '%',
                                'value_type': 'percent',
                                'definition': 'Relative abundance of arbuscular mycorrhizal fungi '
                                              'as a percentage of total microbial biomass.',
                                'interpretation_note': 'Represents the proportional abundance of '
                                                       'arbuscular mycorrhizal fungi within the '
                                                       'microbial community.',
                                'source_reference_group': 'Ward PLFA Biological Report',
                                'aliases': ['AMF percent',
                                            'arbuscular mycorrhizal percent',
                                            'mycorrhizal fungi percent'],
                                'related_terms': ['arbuscular_mycorrhizal_biomass',
                                                  'fungi',
                                                  'mycorrhizae',
                                                  'plfa']},
 'bacteria_pct': {'display_label': 'Bacteria (%)',
                  'source_label': 'Bacteria %',
                  'dataset_family': 'soil_biology_plfa',
                  'group': 'Relative Abundance',
                  'units': '%',
                  'value_type': 'percent',
                  'definition': 'Bacterial PLFA abundance as a percentage of total microbial '
                                'biomass.',
                  'interpretation_note': 'This is a relative abundance measure, not an absolute '
                                         'biomass value.',
                  'source_reference_group': 'Ward PLFA Biological Report',
                  'aliases': ['bacteria percent', 'bacterial relative abundance'],
                  'related_terms': ['bacteria', 'relative_abundance', 'plfa']},
 'fungi_bacteria': {'display_label': 'Fungi:Bacteria Ratio',
                    'source_label': 'Fungi:Bacteria',
                    'dataset_family': 'soil_biology_plfa',
                    'group': 'Ratios and Indices',
                    'units': None,
                    'value_type': 'ratio',
                    'definition': 'Ratio of fungal biomass to bacterial biomass.',
                    'interpretation_note': 'Higher values indicate greater fungal dominance '
                                           'relative to bacteria.',
                    'source_reference_group': 'Ward PLFA Biological Report',
                    'aliases': ['fungi bacteria ratio', 'fungal bacterial ratio'],
                    'related_terms': ['fungi', 'bacteria', 'plfa_ratio']},
 'gram_neg_biomass': {'display_label': 'Gram Negative Bacterial Biomass',
                      'source_label': 'Gram -',
                      'dataset_family': 'soil_biology_plfa',
                      'group': 'Functional Group Biomass',
                      'units': 'ng/g',
                      'value_type': 'biomass',
                      'definition': 'Estimated biomass of gram-negative bacteria based on PLFA '
                                    'biomarkers.',
                      'interpretation_note': 'Higher values indicate greater abundance of '
                                             'gram-negative bacterial biomass.',
                      'source_reference_group': 'Ward PLFA Biological Report',
                      'aliases': ['gram negative biomass', 'gram negative bacteria'],
                      'related_terms': ['bacteria', 'plfa', 'microbial_biomass']},
 'gram_neg_pct': {'display_label': 'Gram Negative Bacteria (%)',
                  'source_label': 'Gram - %',
                  'dataset_family': 'soil_biology_plfa',
                  'group': 'Relative Abundance',
                  'units': '%',
                  'value_type': 'percent',
                  'definition': 'Relative abundance of gram-negative bacteria as a percentage of '
                                'total microbial biomass.',
                  'interpretation_note': 'This represents proportional abundance rather than '
                                         'absolute biomass.',
                  'source_reference_group': 'Ward PLFA Biological Report',
                  'aliases': ['gram negative percent'],
                  'related_terms': ['bacteria', 'relative_abundance', 'plfa']},
 'gram_pos_biomass': {'display_label': 'Gram Positive Bacterial Biomass',
                      'source_label': 'Gram +',
                      'dataset_family': 'soil_biology_plfa',
                      'group': 'Functional Group Biomass',
                      'units': 'ng/g',
                      'value_type': 'biomass',
                      'definition': 'Estimated biomass of gram-positive bacteria based on PLFA '
                                    'biomarkers.',
                      'interpretation_note': 'Higher values indicate greater abundance of '
                                             'gram-positive bacterial biomass.',
                      'source_reference_group': 'Ward PLFA Biological Report',
                      'aliases': ['gram positive biomass', 'gram positive bacteria'],
                      'related_terms': ['bacteria', 'plfa', 'microbial_biomass']},
 'gram_pos_gram_neg_ratio': {'display_label': 'Gram Positive:Gram Negative Ratio',
                             'source_label': 'Gram+:Gram-',
                             'dataset_family': 'soil_biology_plfa',
                             'group': 'Ratios and Indices',
                             'units': None,
                             'value_type': 'ratio',
                             'definition': 'Ratio of gram-positive bacterial biomass to '
                                           'gram-negative bacterial biomass.',
                             'interpretation_note': 'Used as an indicator of microbial community '
                                                    'structure and potential stress response.',
                             'source_reference_group': 'Ward PLFA Biological Report',
                             'aliases': ['gram positive gram negative ratio',
                                         'gram+/gram- ratio',
                                         'gram_pos_gram'],
                             'related_terms': ['gram_pos_biomass',
                                               'gram_neg_biomass',
                                               'plfa_ratio']},
 'gram_pos_pct': {'display_label': 'Gram Positive Bacteria (%)',
                  'source_label': 'Gram + %',
                  'dataset_family': 'soil_biology_plfa',
                  'group': 'Relative Abundance',
                  'units': '%',
                  'value_type': 'percent',
                  'definition': 'Relative abundance of gram-positive bacteria as a percentage of '
                                'total microbial biomass.',
                  'interpretation_note': 'This represents proportional abundance rather than '
                                         'absolute biomass.',
                  'source_reference_group': 'Ward PLFA Biological Report',
                  'aliases': ['gram positive percent'],
                  'related_terms': ['bacteria', 'relative_abundance', 'plfa']},
 'monounsaturated': {'display_label': 'Monounsaturated Fatty Acid Biomass',
                     'source_label': 'MonoUnsaturated',
                     'dataset_family': 'soil_biology_plfa',
                     'group': 'Fatty Acid Pools',
                     'units': 'ng/g',
                     'value_type': 'biomass',
                     'definition': 'Estimated biomass associated with monounsaturated fatty acid '
                                   'PLFA biomarkers.',
                     'interpretation_note': 'Monounsaturated fatty acid pools may reflect shifts '
                                            'in microbial community composition and physiological '
                                            'condition.',
                     'source_reference_group': 'Ward PLFA Biological Report',
                     'aliases': ['mono unsaturated', 'monounsaturated fatty acids'],
                     'related_terms': ['unsaturated',
                                       'polyunsaturated',
                                       'monounsaturated_polyunsaturated_ratio',
                                       'plfa']},
 'monounsaturated_polyunsaturated_ratio': {'display_label': 'Monounsaturated:Polyunsaturated Fatty '
                                                            'Acid Ratio',
                                           'source_label': 'Mono:Poly',
                                           'dataset_family': 'soil_biology_plfa',
                                           'group': 'Ratios and Indices',
                                           'units': None,
                                           'value_type': 'ratio',
                                           'definition': 'Ratio of monounsaturated fatty acid '
                                                         'biomass to polyunsaturated fatty acid '
                                                         'biomass.',
                                           'interpretation_note': 'Used as a PLFA stress and '
                                                                  'microbial community structure '
                                                                  'indicator.',
                                           'source_reference_group': 'Ward PLFA Biological Report',
                                           'aliases': ['mono_poly',
                                                       'mono poly ratio',
                                                       'MUFA:PUFA ratio'],
                                           'related_terms': ['monounsaturated',
                                                             'polyunsaturated',
                                                             'plfa_ratio']},
 'polyunsaturated': {'display_label': 'Polyunsaturated Fatty Acid Biomass',
                     'source_label': 'PolyUnsaturated',
                     'dataset_family': 'soil_biology_plfa',
                     'group': 'Fatty Acid Pools',
                     'units': 'ng/g',
                     'value_type': 'biomass',
                     'definition': 'Estimated biomass associated with polyunsaturated fatty acid '
                                   'PLFA biomarkers.',
                     'interpretation_note': 'Polyunsaturated fatty acid pools are often associated '
                                            'with fungal and eukaryotic microbial components.',
                     'source_reference_group': 'Ward PLFA Biological Report',
                     'aliases': ['poly unsaturated', 'polyunsaturated fatty acids'],
                     'related_terms': ['unsaturated',
                                       'monounsaturated',
                                       'monounsaturated_polyunsaturated_ratio',
                                       'plfa']},
 'predator_prey': {'display_label': 'Predator:Prey Ratio',
                   'source_label': 'Predator:Prey',
                   'dataset_family': 'soil_biology_plfa',
                   'group': 'Ratios and Indices',
                   'units': None,
                   'value_type': 'ratio',
                   'definition': 'Ratio of predator-associated PLFA biomass to prey-associated '
                                 'PLFA biomass.',
                   'interpretation_note': 'Used as an indicator of microbial food-web structure. '
                                          'Higher values may indicate greater predator '
                                          'representation relative to prey groups.',
                   'source_reference_group': 'Ward PLFA Biological Report',
                   'aliases': ['predator prey ratio', 'predator:prey'],
                   'related_terms': ['protozoa_biomass', 'bacteria', 'fungi', 'plfa_ratio']},
 'protozoa_biomass': {'display_label': 'Protozoa Biomass',
                      'source_label': 'Protozoa',
                      'dataset_family': 'soil_biology_plfa',
                      'group': 'Functional Group Biomass',
                      'units': 'ng/g',
                      'value_type': 'biomass',
                      'definition': 'Estimated protozoa-associated biomass based on PLFA '
                                    'biomarkers.',
                      'interpretation_note': 'Protozoa are microbial predators and can indicate '
                                             'soil food-web activity.',
                      'source_reference_group': 'Ward PLFA Biological Report',
                      'aliases': ['protozoa biomass', 'protozoan biomass'],
                      'related_terms': ['protozoa', 'predator_prey', 'plfa', 'microbial_biomass']},
 'protozoan_pct': {'display_label': 'Protozoa (%)',
                   'source_label': 'Protozoa %',
                   'dataset_family': 'soil_biology_plfa',
                   'group': 'Relative Abundance',
                   'units': '%',
                   'value_type': 'percent',
                   'definition': 'Relative abundance of protozoa-associated biomarkers as a '
                                 'percentage of total microbial biomass.',
                   'interpretation_note': 'Protozoa are microbial predators and can reflect soil '
                                          'food-web structure.',
                   'source_reference_group': 'Ward PLFA Biological Report',
                   'aliases': ['protozoa percent', 'protozoan percent'],
                   'related_terms': ['protozoa_biomass', 'predator_prey', 'plfa']},
 'rhizobia_biomass': {'display_label': 'Rhizobia Biomass',
                      'source_label': 'Rhizobia',
                      'dataset_family': 'soil_biology_plfa',
                      'group': 'Functional Group Biomass',
                      'units': 'ng/g',
                      'value_type': 'biomass',
                      'definition': 'Estimated biomass of rhizobia-associated microbial '
                                    'biomarkers.',
                      'interpretation_note': 'Rhizobia are bacteria commonly associated with '
                                             'nitrogen-fixing relationships with legumes.',
                      'source_reference_group': 'Ward PLFA Biological Report',
                      'aliases': ['rhizobia biomass', 'rhizobial biomass'],
                      'related_terms': ['bacteria',
                                        'nitrogen_fixation',
                                        'plfa',
                                        'microbial_biomass']},
 'rhizobia_pct': {'display_label': 'Rhizobia (%)',
                  'source_label': 'Rhizobia %',
                  'dataset_family': 'soil_biology_plfa',
                  'group': 'Relative Abundance',
                  'units': '%',
                  'value_type': 'percent',
                  'definition': 'Relative abundance of rhizobia-associated biomarkers as a '
                                'percentage of total microbial biomass.',
                  'interpretation_note': 'This represents proportional abundance rather than '
                                         'absolute biomass.',
                  'source_reference_group': 'Ward PLFA Biological Report',
                  'aliases': ['rhizobia percent'],
                  'related_terms': ['rhizobia_biomass', 'bacteria', 'plfa']},
 'saprophytes_biomass': {'display_label': 'Saprophyte Biomass',
                         'source_label': 'Saprophytes',
                         'dataset_family': 'soil_biology_plfa',
                         'group': 'Functional Group Biomass',
                         'units': 'ng/g',
                         'value_type': 'biomass',
                         'definition': 'Estimated biomass of saprophytic organisms based on PLFA '
                                       'biomarkers.',
                         'interpretation_note': 'Saprophytes are associated with decomposition of '
                                                'dead organic matter.',
                         'source_reference_group': 'Ward PLFA Biological Report',
                         'aliases': ['saprophyte biomass', 'saprophytic biomass', 'saprophytes'],
                         'related_terms': ['fungi', 'decomposition', 'plfa', 'microbial_biomass']},
 'saprophytic_pct': {'display_label': 'Saprophytes (%)',
                     'source_label': 'Saprophytes %',
                     'dataset_family': 'soil_biology_plfa',
                     'group': 'Relative Abundance',
                     'units': '%',
                     'value_type': 'percent',
                     'definition': 'Relative abundance of saprophytic organisms as a percentage of '
                                   'total microbial biomass.',
                     'interpretation_note': 'Saprophytes are associated with decomposition of dead '
                                            'organic matter.',
                     'source_reference_group': 'Ward PLFA Biological Report',
                     'aliases': ['saprophyte percent', 'saprophytic percent'],
                     'related_terms': ['saprophytes_biomass', 'decomposition', 'fungi', 'plfa']},
 'saturated': {'display_label': 'Saturated Fatty Acid Biomass',
               'source_label': 'Saturated',
               'dataset_family': 'soil_biology_plfa',
               'group': 'Fatty Acid Pools',
               'units': 'ng/g',
               'value_type': 'biomass',
               'definition': 'Estimated biomass associated with saturated fatty acid PLFA '
                             'biomarkers.',
               'interpretation_note': 'Used in PLFA stress and community structure interpretation.',
               'source_reference_group': 'Ward PLFA Biological Report',
               'aliases': ['saturated fatty acids'],
               'related_terms': ['plfa', 'fatty_acids']},
 'saturated_unsaturated_ratio': {'display_label': 'Saturated:Unsaturated Fatty Acid Ratio',
                                 'source_label': 'Sat:Unsat',
                                 'dataset_family': 'soil_biology_plfa',
                                 'group': 'Ratios and Indices',
                                 'units': None,
                                 'value_type': 'ratio',
                                 'definition': 'Ratio of saturated fatty acid biomass to '
                                               'unsaturated fatty acid biomass.',
                                 'interpretation_note': 'Used as a PLFA stress and microbial '
                                                        'community structure indicator.',
                                 'source_reference_group': 'Ward PLFA Biological Report',
                                 'aliases': ['sat_unsat',
                                             'saturated unsaturated ratio',
                                             'saturated:unsaturated ratio'],
                                 'related_terms': ['saturated', 'unsaturated', 'plfa_ratio']},
 'total_bacteria_biomass': {'display_label': 'Total Bacterial Biomass',
                            'source_label': 'Total Bacteria',
                            'dataset_family': 'soil_biology_plfa',
                            'group': 'Functional Group Biomass',
                            'units': 'ng/g',
                            'value_type': 'biomass',
                            'definition': 'Estimated living bacterial biomass based on PLFA '
                                          'biomarkers.',
                            'interpretation_note': 'Higher values generally indicate greater '
                                                   'bacterial biomass.',
                            'source_reference_group': 'Ward PLFA Biological Report',
                            'aliases': ['total bacteria', 'bacterial biomass'],
                            'related_terms': ['bacteria', 'plfa', 'microbial_biomass']},
 'total_biomass': {'display_label': 'Total Living Microbial Biomass',
                   'dataset_family': 'soil_biology_plfa',
                   'group': 'Microbial Biomass',
                   'units': 'ng/g',
                   'value_type': 'biomass',
                   'definition': 'Total living microbial biomass estimated from PLFA biomarkers.',
                   'interpretation_note': 'Higher values generally indicate greater living '
                                          'microbial biomass.',
                   'source_reference_group': 'Ward PLFA Biological Report',
                   'aliases': ['Total Biomass', 'Total Living Microbial Biomass'],
                   'related_terms': ['plfa', 'microbial_biomass']},
 'total_fungi_biomass': {'display_label': 'Total Fungal Biomass',
                         'source_label': 'Total Fungi',
                         'dataset_family': 'soil_biology_plfa',
                         'group': 'Functional Group Biomass',
                         'units': 'ng/g',
                         'value_type': 'biomass',
                         'definition': 'Estimated total fungal biomass based on PLFA biomarkers.',
                         'interpretation_note': 'Higher values indicate greater fungal biomass in '
                                                'the soil microbial community.',
                         'source_reference_group': 'Ward PLFA Biological Report',
                         'aliases': ['total fungi biomass', 'fungal biomass', 'total fungi'],
                         'related_terms': ['fungi', 'plfa', 'microbial_biomass']},
 'total_fungi_pct': {'display_label': 'Total Fungi (%)',
                     'source_label': 'Total Fungi %',
                     'dataset_family': 'soil_biology_plfa',
                     'group': 'Relative Abundance',
                     'units': '%',
                     'value_type': 'percent',
                     'definition': 'Relative abundance of fungal biomass as a percentage of total '
                                   'microbial biomass.',
                     'interpretation_note': 'Higher values indicate greater fungal dominance '
                                            'within the microbial community.',
                     'source_reference_group': 'Ward PLFA Biological Report',
                     'aliases': ['fungi percent', 'fungal percent', 'total fungi percent'],
                     'related_terms': ['total_fungi_biomass', 'fungi', 'plfa']},
 'undifferentiated_biomass': {'display_label': 'Undifferentiated Microbial Biomass',
                              'source_label': 'Undifferentiated',
                              'dataset_family': 'soil_biology_plfa',
                              'group': 'Functional Group Biomass',
                              'units': 'ng/g',
                              'value_type': 'biomass',
                              'definition': 'Estimated PLFA biomass not assigned to a more '
                                            'specific microbial functional group.',
                              'interpretation_note': 'This category captures microbial biomass '
                                                     'that is not differentiated into the named '
                                                     'functional groups.',
                              'source_reference_group': 'Ward PLFA Biological Report',
                              'aliases': ['undifferentiated biomass',
                                          'unclassified microbial biomass'],
                              'related_terms': ['plfa', 'microbial_biomass']},
 'undifferentiated_pct': {'display_label': 'Undifferentiated Biomass (%)',
                          'source_label': 'Undifferentiated %',
                          'dataset_family': 'soil_biology_plfa',
                          'group': 'Relative Abundance',
                          'units': '%',
                          'value_type': 'percent',
                          'definition': 'Relative abundance of undifferentiated microbial biomass '
                                        'as a percentage of total microbial biomass.',
                          'interpretation_note': 'Represents microbial biomass not classified into '
                                                 'the named functional groups.',
                          'source_reference_group': 'Ward PLFA Biological Report',
                          'aliases': ['undifferentiated percent', 'unclassified biomass percent'],
                          'related_terms': ['undifferentiated_biomass',
                                            'plfa',
                                            'microbial_biomass']},
 'unsaturated': {'display_label': 'Unsaturated Fatty Acid Biomass',
                 'source_label': 'Unsaturated',
                 'dataset_family': 'soil_biology_plfa',
                 'group': 'Fatty Acid Pools',
                 'units': 'ng/g',
                 'value_type': 'biomass',
                 'definition': 'Estimated biomass associated with unsaturated fatty acid PLFA '
                               'biomarkers.',
                 'interpretation_note': 'Unsaturated fatty acid pools are commonly used in '
                                        'microbial community structure and physiological stress '
                                        'interpretation.',
                 'source_reference_group': 'Ward PLFA Biological Report',
                 'aliases': ['unsaturated fatty acids', 'unsaturated PLFA pool'],
                 'related_terms': ['saturated',
                                   'monounsaturated',
                                   'polyunsaturated',
                                   'saturated_unsaturated_ratio',
                                   'monounsaturated_polyunsaturated_ratio',
                                   'plfa']},

 "pre_16_1_w7c": {
     "display_label": "Pre 16:1 ω7c Biomarker",
     "source_label": "Pre 16:1 w7c",
     "dataset_family": "soil_biology_plfa",
     "group": "Stress Biomarkers",
     "units": "ng/g",
     "value_type": "biomass",
     "definition": "Estimated biomass associated with the 16:1 ω7c precursor PLFA biomarker.",
     "interpretation_note": "Used with cyclo 17:0 to calculate a PLFA stress ratio.",
     "source_reference_group": "Ward PLFA Biological Report",
     "aliases": ["pre 16:1 w7c", "16:1 w7c precursor"],
     "related_terms": ["cyclo_17_0", "pre_16_1w7c_cy17_0", "plfa_stress"],
 },

 "cyclo_17_0": {
     "display_label": "Cyclo 17:0 Biomarker",
     "source_label": "Cyclo 17:0",
     "dataset_family": "soil_biology_plfa",
     "group": "Stress Biomarkers",
     "units": "ng/g",
     "value_type": "biomass",
     "definition": "Estimated biomass associated with the cyclopropyl 17:0 PLFA biomarker.",
     "interpretation_note": "Used with pre 16:1 ω7c to calculate a PLFA stress ratio.",
     "source_reference_group": "Ward PLFA Biological Report",
     "aliases": ["cyclo 17:0", "cy17:0"],
     "related_terms": ["pre_16_1_w7c", "pre_16_1w7c_cy17_0", "plfa_stress"],
 },

 "pre_16_1w7c_cy17_0": {
     "display_label": "Pre 16:1 ω7c:Cyclo 17:0 Ratio",
     "source_label": "Pre 16:1w7c/Cy17:0",
     "dataset_family": "soil_biology_plfa",
     "group": "Stress Ratios",
     "units": None,
     "value_type": "ratio",
     "definition": "Ratio comparing the 16:1 ω7c precursor biomarker with cyclo 17:0.",
     "interpretation_note": "Used as a PLFA physiological stress indicator.",
     "source_reference_group": "Ward PLFA Biological Report",
     "aliases": ["pre 16:1w7c cy17:0 ratio", "16:1w7c/cy17:0"],
     "related_terms": ["pre_16_1_w7c", "cyclo_17_0", "plfa_stress"],
 },

 "pre_18_1_w7c": {
     "display_label": "Pre 18:1 ω7c Biomarker",
     "source_label": "Pre 18:1 w7c",
     "dataset_family": "soil_biology_plfa",
     "group": "Stress Biomarkers",
     "units": "ng/g",
     "value_type": "biomass",
     "definition": "Estimated biomass associated with the 18:1 ω7c precursor PLFA biomarker.",
     "interpretation_note": "Used with cyclo 19:0 to calculate a PLFA stress ratio.",
     "source_reference_group": "Ward PLFA Biological Report",
     "aliases": ["pre 18:1 w7c", "18:1 w7c precursor"],
     "related_terms": ["cyclo_19_0", "pre_18_1w7c_cy19_0", "plfa_stress"],
 },

 "cyclo_19_0": {
     "display_label": "Cyclo 19:0 Biomarker",
     "source_label": "Cyclo 19:0",
     "dataset_family": "soil_biology_plfa",
     "group": "Stress Biomarkers",
     "units": "ng/g",
     "value_type": "biomass",
     "definition": "Estimated biomass associated with the cyclopropyl 19:0 PLFA biomarker.",
     "interpretation_note": "Used with pre 18:1 ω7c to calculate a PLFA stress ratio.",
     "source_reference_group": "Ward PLFA Biological Report",
     "aliases": ["cyclo 19:0", "cy19:0"],
     "related_terms": ["pre_18_1_w7c", "pre_18_1w7c_cy19_0", "plfa_stress"],
 },

 "pre_18_1w7c_cy19_0": {
     "display_label": "Pre 18:1 ω7c:Cyclo 19:0 Ratio",
     "source_label": "Pre 18:1w7c/Cy19:0",
     "dataset_family": "soil_biology_plfa",
     "group": "Stress Ratios",
     "units": None,
     "value_type": "ratio",
     "definition": "Ratio comparing the 18:1 ω7c precursor biomarker with cyclo 19:0.",
     "interpretation_note": "Used as a PLFA physiological stress indicator.",
     "source_reference_group": "Ward PLFA Biological Report",
     "aliases": ["pre 18:1w7c cy19:0 ratio", "18:1w7c/cy19:0"],
     "related_terms": ["pre_18_1_w7c", "cyclo_19_0", "plfa_stress"],
 },

 "diversity_index": {
     "display_label": "Functional Group Diversity Index",
     "source_label": "Diversity Index",
     "dataset_family": "soil_biology_plfa",
     "group": "Ratios and Indices",
     "units": None,
     "value_type": "index",
     "definition": "Index summarizing microbial functional group diversity based on PLFA results.",
     "interpretation_note": "Higher values generally indicate greater microbial functional diversity.",
     "source_reference_group": "Ward PLFA Biological Report",
     "aliases": ["diversity index", "functional group diversity index"],
     "related_terms": ["plfa", "microbial_diversity"],
 }
}

def get_lab_variable_metadata(key: str) -> dict:
    return LAB_VARIABLE_METADATA.get(key, {})

def get_display_label(key: str) -> str:
    return LAB_VARIABLE_METADATA.get(key, {}).get("display_label", key)

def get_units(key: str) -> str | None:
    return LAB_VARIABLE_METADATA.get(key, {}).get("units")
