# biochar_app/scripts/bulk_downloads.py

from __future__ import annotations

import io
import json
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional

import pandas as pd
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse

# --------------------------------------------------------------------------------------
# Router
# --------------------------------------------------------------------------------------

bulk_router = APIRouter()

# --------------------------------------------------------------------------------------
# Paths / conventions (adjust if your project differs)
# --------------------------------------------------------------------------------------

PARQUET_ROOT = Path("biochar_app/data-processed/parquet")  # matches your Finder screenshot
WEATHER_DIRNAME = "weather"  # you have /{year}/{resolution}/weather/...

IRRIGATION_WORKBOOK_PATH = Path("biochar_app/data-raw/biochar-data-master.xlsx")

# If you want to expose only a subset
ALLOWED_RESOLUTIONS = ["15min", "hourly", "daily", "monthly", "gseason"]


# --------------------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------------------

def _safe_int(v: Any) -> Optional[int]:
    try:
        i = int(v)
        return i
    except Exception:
        return None


def _list_years_on_disk() -> list[int]:
    if not PARQUET_ROOT.exists():
        return []
    years: list[int] = []
    for p in PARQUET_ROOT.iterdir():
        if p.is_dir():
            y = _safe_int(p.name)
            if y is not None:
                years.append(y)
    return sorted(set(years))


def _list_resolutions_on_disk(year: int) -> list[str]:
    ydir = PARQUET_ROOT / str(year)
    if not ydir.exists():
        return []
    res = [p.name for p in ydir.iterdir() if p.is_dir() and p.name in ALLOWED_RESOLUTIONS]
    return sorted(set(res), key=lambda s: ALLOWED_RESOLUTIONS.index(s) if s in ALLOWED_RESOLUTIONS else 999)


def _logger_parquet_path(year: int, resolution: str) -> Path:
    # In your screenshot: .../parquet/2025/monthly/2025_monthly.parquet
    return PARQUET_ROOT / str(year) / resolution / f"{year}_{resolution}.parquet"


def _weather_parquet_path(year: int, resolution: str) -> Path:
    # In your screenshot: .../parquet/2025/monthly/weather/2025_monthly_weather.parquet (or similar)
    # We’ll try a couple common patterns.
    base = PARQUET_ROOT / str(year) / resolution / WEATHER_DIRNAME
    candidates = [
        base / f"{year}_{resolution}_weather.parquet",
        base / f"{year}_{resolution}.parquet",
        base / f"weather_{year}_{resolution}.parquet",
    ]
    for c in candidates:
        if c.exists():
            return c
    # If none exist, return the first candidate for error messaging
    return candidates[0]


def _read_parquet_to_csv_bytes(path: Path) -> bytes:
    if not path.exists():
        raise HTTPException(status_code=404, detail=f"Parquet not found: {path}")
    try:
        df = pd.read_parquet(path)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to read parquet {path}: {e}")
    # NOTE: index usually not desired for downloads
    return df.to_csv(index=False).encode("utf-8")


def _read_workbook_sheet_to_csv_bytes(sheet_name: str) -> bytes:
    if not IRRIGATION_WORKBOOK_PATH.exists():
        raise HTTPException(status_code=404, detail=f"Workbook not found: {IRRIGATION_WORKBOOK_PATH}")
    try:
        df = pd.read_excel(IRRIGATION_WORKBOOK_PATH, sheet_name=sheet_name, engine="openpyxl")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to read sheet {sheet_name}: {e}")
    return df.to_csv(index=False).encode("utf-8")


def _zip_bytes(files: list[tuple[str, bytes]]) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        for name, content in files:
            zf.writestr(name, content)
    buf.seek(0)
    return buf.read()


def _readme_text(dataset: str, year: Optional[int], resolution: Optional[str], notes: str = "") -> str:
    ytxt = str(year) if year is not None else "ALL/NA"
    rtxt = resolution if resolution is not None else "ALL/NA"
    base = f"""Biochar Fruita CSU – Bulk Download

Dataset: {dataset}
Year: {ytxt}
Resolution: {rtxt}

Notes
-----
{notes or "See website Technical Details for variable definitions and units."}

Units
-----
Stored data are in US customary units in the backend (display may be metric if toggled).

Generated by the Biochar dashboard bulk download endpoint.
"""
    return base


# --------------------------------------------------------------------------------------
# Manifest
# --------------------------------------------------------------------------------------

@bulk_router.get("/bulk_download_manifest")
def bulk_download_manifest() -> list[dict[str, Any]]:
    """
    Returns a manifest of what can be downloaded.
    We derive logger/weather availability from the parquet folder layout on disk.
    We derive workbook-based (irrigation/fertilizing/biomass) availability from sheet names.
    """
    items: list[dict[str, Any]] = []

    # 1) Logger + weather: per year + per resolution, derived from disk
    years = _list_years_on_disk()
    for y in years:
        res_list = _list_resolutions_on_disk(y)
        for res in res_list:
            lp = _logger_parquet_path(y, res)
            if lp.exists():
                items.append({
                    "key": f"loggers_{y}_{res}",
                    "dataset": "loggers",
                    "year": y,
                    "resolution": res,
                    "label": f"Logger data ({y}, {res})",
                })
            wp = _weather_parquet_path(y, res)
            if wp.exists():
                items.append({
                    "key": f"weather_{y}_{res}",
                    "dataset": "weather",
                    "year": y,
                    "resolution": res,
                    "label": f"Weather data ({y}, {res})",
                })

    # 2) Workbook-derived datasets: expose by year if sheets exist
    if IRRIGATION_WORKBOOK_PATH.exists():
        try:
            xls = pd.ExcelFile(IRRIGATION_WORKBOOK_PATH, engine="openpyxl")
            sheets = [s.strip() for s in xls.sheet_names]
        except Exception:
            sheets = []

        # Map “dataset base” -> sheet contains token
        # Adjust tokens to match your actual workbook sheet naming conventions.
        workbook_rules = [
            ("irrigation", "IRRIGATION"),
            ("fertilizing", "FERTIL"),
            ("biomass", "BIOMASS"),
        ]

        for base, token in workbook_rules:
            for s in sheets:
                if token in s.upper():
                    # infer year from sheet name: any 4-digit number
                    year = None
                    for part in s.replace("-", " ").replace("_", " ").split():
                        if len(part) == 4 and part.isdigit():
                            year = int(part)
                            break
                    if year is None:
                        continue
                    items.append({
                        "key": f"{base}_{year}",
                        "dataset": base,
                        "year": year,
                        "resolution": None,
                        "label": f"{base.title()} ({year})",
                        "workbook_sheet": s,
                    })

    return items


# --------------------------------------------------------------------------------------
# Download
# --------------------------------------------------------------------------------------

@bulk_router.post("/bulk_download")
async def bulk_download(payload: dict[str, Any]):
    """
    Payload supports:
      - {"key": "loggers_2025_daily"} OR
      - {"keys": ["loggers_2025_daily"]}  (your current JS uses keys: [key])
    """
    keys = payload.get("keys")
    if isinstance(keys, list) and keys:
        key = str(keys[0])
    else:
        key = str(payload.get("key") or "").strip()

    if not key:
        raise HTTPException(status_code=400, detail="Missing key (or keys[0])")

    # Parse key patterns
    #  - loggers_{year}_{res}
    #  - weather_{year}_{res}
    #  - irrigation_{year}
    #  - fertilizing_{year}
    #  - biomass_{year}
    parts = key.split("_")
    if len(parts) < 2:
        raise HTTPException(status_code=400, detail=f"Unrecognized key format: {key}")

    dataset = parts[0].lower()

    files: list[tuple[str, bytes]] = []
    zip_name = f"biochar_{key}.zip"

    # Logger / Weather (parquet → csv)
    if dataset in {"loggers", "weather"}:
        if len(parts) < 3:
            raise HTTPException(status_code=400, detail=f"Expected {dataset}_YYYY_resolution key, got: {key}")
        year = _safe_int(parts[1])
        resolution = parts[2]
        if year is None:
            raise HTTPException(status_code=400, detail=f"Invalid year in key: {key}")
        if resolution not in ALLOWED_RESOLUTIONS:
            raise HTTPException(status_code=400, detail=f"Invalid resolution '{resolution}' in key: {key}")

        if dataset == "loggers":
            pq = _logger_parquet_path(year, resolution)
            csv_bytes = _read_parquet_to_csv_bytes(pq)
            csv_name = f"biochar_loggers_{year}_{resolution}.csv"
            readme = _readme_text("logger", year, resolution, notes=f"Source: {pq}")
        else:
            pq = _weather_parquet_path(year, resolution)
            csv_bytes = _read_parquet_to_csv_bytes(pq)
            csv_name = f"biochar_weather_{year}_{resolution}.csv"
            readme = _readme_text("weather", year, resolution, notes=f"Source: {pq}")

        files.append((csv_name, csv_bytes))
        files.append(("README.txt", readme.encode("utf-8")))

    # Workbook-based (sheet → csv)
    elif dataset in {"irrigation", "fertilizing", "biomass"}:
        year = _safe_int(parts[1]) if len(parts) >= 2 else None
        if year is None:
            raise HTTPException(status_code=400, detail=f"Invalid year in key: {key}")

        # Find the matching sheet from the manifest logic
        try:
            xls = pd.ExcelFile(IRRIGATION_WORKBOOK_PATH, engine="openpyxl")
            sheets = [s.strip() for s in xls.sheet_names]
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Cannot read workbook sheets: {e}")

        token = {
            "irrigation": "IRRIGATION",
            "fertilizing": "FERTIL",
            "biomass": "BIOMASS",
        }[dataset]

        sheet = None
        for s in sheets:
            s_up = s.upper()
            if token in s_up and str(year) in s_up:
                sheet = s
                break

        if not sheet:
            raise HTTPException(status_code=404, detail=f"No workbook sheet found for {dataset} {year}")

        csv_bytes = _read_workbook_sheet_to_csv_bytes(sheet)
        csv_name = f"biochar_{dataset}_{year}.csv"
        readme = _readme_text(dataset, year, None, notes=f"Source workbook: {IRRIGATION_WORKBOOK_PATH}\nSheet: {sheet}")

        files.append((csv_name, csv_bytes))
        files.append(("README.txt", readme.encode("utf-8")))

    else:
        raise HTTPException(status_code=400, detail=f"Unknown dataset in key: {key}")

    zip_bytes = _zip_bytes(files)

    return StreamingResponse(
        io.BytesIO(zip_bytes),
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{zip_name}"'},
    )