from __future__ import annotations

import io
import zipfile
from pathlib import Path
from typing import Any, Optional

import pandas as pd
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse

from biochar_app.config.paths import (
    PARQUET_DIR,
    PARQUET_SUMMARY_DIR,
    PARQUET_SUMMARY_WEATHER_15MIN_DIR,
    PARQUET_SUMMARY_WEATHER_HOURLY_DIR,
    PARQUET_SUMMARY_WEATHER_DAILY_DIR,
    PARQUET_SUMMARY_WEATHER_MONTHLY_DIR,
    WARD_MASTER_SOILCHEM_CSV,
    WARD_MASTER_SOILBIO_CSV,
    WARD_MASTER_NIR_CSV,
    IRRIGATION_CSV,
    FERTILIZER_CSV,
)
from biochar_app.scripts.data_loading import load_logger_data, load_weather_data

# --------------------------------------------------------------------------------------
# Router
# --------------------------------------------------------------------------------------

bulk_router = APIRouter()

# --------------------------------------------------------------------------------------
# Paths / conventions
# --------------------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parents[2]
IRRIGATION_WORKBOOK_PATH = REPO_ROOT / "biochar_app" / "data-raw" / "biochar-data-master.xlsx"

ALLOWED_RESOLUTIONS = ["15min", "hourly", "daily", "monthly", "gseason"]

FILE_BACKED_DOWNLOADS: dict[str, tuple[str, Path, str]] = {
    "soil_chem_all": (
        "Soil Chemistry (all years)",
        WARD_MASTER_SOILCHEM_CSV,
        "biochar_soil_chemistry_all_years.csv",
    ),
    "soil_bio_all": (
        "Soil Biology (all years)",
        WARD_MASTER_SOILBIO_CSV,
        "biochar_soil_biology_all_years.csv",
    ),
    "hay_all": (
        "Biomass / Hay NIR (all years)",
        WARD_MASTER_NIR_CSV,
        "biochar_biomass_hay_all_years.csv",
    ),
}

MANAGEMENT_DATASETS = {
    "irrigation": (
        IRRIGATION_CSV,
        "Irrigation",
        "biochar_irrigation_all_years.csv",
    ),
    "fertilizer": (
        FERTILIZER_CSV,
        "Fertilizer use",
        "biochar_fertilizer_all_years.csv",
    ),
}

WORKBOOK_TOKENS: dict[str, str] = {
    "biomass": "BIOMASS",
}

# --------------------------------------------------------------------------------------
# Small helpers
# --------------------------------------------------------------------------------------


def _safe_int(v: Any) -> Optional[int]:
    try:
        return int(v)
    except Exception:
        return None


def _detect_year_span(df: pd.DataFrame) -> str:
    candidate_date_cols = [
        "date_rec",
        "date",
        "sample_date",
        "date_rept",
        "start_timestamp",
        "end_timestamp",
        "application_date",
        "timestamp",
    ]
    candidate_year_cols = ["year", "Year"]

    for col in candidate_date_cols:
        if col in df.columns:
            dt = pd.to_datetime(df[col], errors="coerce")
            years = sorted(y for y in dt.dt.year.dropna().astype(int).unique())
            if years:
                return f"{years[0]}–{years[-1]}" if len(years) > 1 else str(years[0])

    for col in candidate_year_cols:
        if col in df.columns:
            vals = pd.to_numeric(df[col], errors="coerce").dropna().astype(int)
            years = sorted(vals.unique())
            if years:
                return f"{years[0]}–{years[-1]}" if len(years) > 1 else str(years[0])

    return "unknown"


def _dataset_summary(df: pd.DataFrame) -> str:
    rows = len(df)
    cols = len(df.columns)
    year_text = _detect_year_span(df)

    return f"""Dataset summary
---------------
Rows: {rows}
Variables: {cols}
Years included: {year_text}
"""


def _file_backed_readme_text(
    dataset_label: str,
    source_path: Path,
    df: pd.DataFrame,
) -> str:
    summary = _dataset_summary(df)

    return f"""Biochar Fruita CSU – Bulk Download

Dataset: {dataset_label}
Source file: {source_path}

{summary}

Notes
-----
This archive contains the canonical all-years CSV currently used by the Biochar dashboard.

Units
-----
See the Technical Details tab and dataset-specific documentation for variable definitions and units.

Generated by the Biochar dashboard bulk download endpoint.
"""


def _readme_text(
    dataset: str,
    year: Optional[int],
    resolution: Optional[str],
    notes: str = "",
    df: Optional[pd.DataFrame] = None,
) -> str:
    ytxt = str(year) if year is not None else "ALL/NA"
    rtxt = resolution if resolution is not None else "ALL/NA"

    summary = ""
    if df is not None:
        summary = "\n" + _dataset_summary(df)

    return f"""Biochar Fruita CSU – Bulk Download

Dataset: {dataset}
Year: {ytxt}
Resolution: {rtxt}
{summary}

Notes
-----
{notes or "See tab 'Technical Details' for variable definitions and units."}

Units
-----
Stored data are in US customary units in the backend (display may be metric if toggled).

Generated by the Biochar dashboard bulk download endpoint.
"""


def _list_years_on_disk() -> list[int]:
    years: set[int] = set()

    if PARQUET_SUMMARY_DIR.exists():
        for res_dir in PARQUET_SUMMARY_DIR.iterdir():
            if not res_dir.is_dir():
                continue
            for p in res_dir.glob("*.parquet"):
                stem = p.stem
                y = _safe_int(stem.split("_", 1)[0])
                if y is not None and 1900 <= y <= 2100:
                    years.add(y)

    if PARQUET_DIR.exists():
        for p in PARQUET_DIR.iterdir():
            if p.is_dir():
                y = _safe_int(p.name)
                if y is not None:
                    years.add(y)

    return sorted(years)


def _list_resolutions_on_disk(year: int) -> list[str]:
    found: list[str] = []

    for res in ALLOWED_RESOLUTIONS:
        if _summary_logger_parquet_path(year, res).exists():
            found.append(res)

    return [r for r in ALLOWED_RESOLUTIONS if r in found]


def _extract_years_from_dataframe(df: pd.DataFrame) -> list[int]:
    candidate_date_cols = [
        "start_timestamp",
        "application_date",
        "date",
        "timestamp",
        "date_rec",
        "end_timestamp",
    ]
    candidate_year_cols = ["year", "Year"]

    for col in candidate_date_cols:
        if col in df.columns:
            dt = pd.to_datetime(
                df[col],
                format="ISO8601",
                errors="coerce"
            )
            years = sorted(int(y) for y in dt.dt.year.dropna().astype(int).unique())
            if years:
                return years

    for col in candidate_year_cols:
        if col in df.columns:
            vals = pd.to_numeric(df[col], errors="coerce").dropna().astype(int)
            years = sorted(int(y) for y in vals.unique())
            if years:
                return years

    return []


def _filter_management_df_to_year(df: pd.DataFrame, dataset: str, year: int) -> pd.DataFrame:
    out = df.copy()

    if dataset == "irrigation":
        if "start_timestamp" not in out.columns:
            raise HTTPException(
                status_code=500,
                detail="Irrigation CSV missing required column: start_timestamp",
            )

        start_ts = pd.to_datetime(out["start_timestamp"], errors="coerce")
        out = out.assign(_year=start_ts.dt.year)
        out = out[out["_year"] == year].copy()
        out.drop(columns=["_year"], inplace=True, errors="ignore")
        return out

    date_candidates = [
        "application_date",
        "date",
        "timestamp",
        "start_timestamp",
    ]
    for col in date_candidates:
        if col in out.columns:
            ts = pd.to_datetime(out[col], errors="coerce")
            out = out.assign(_year=ts.dt.year)
            out = out[out["_year"] == year].copy()
            out.drop(columns=["_year"], inplace=True, errors="ignore")
            return out

    for col in ("year", "Year"):
        if col in out.columns:
            yrs = pd.to_numeric(out[col], errors="coerce")
            return out[yrs == year].copy()

    raise HTTPException(
        status_code=500,
        detail=f"Could not infer year for management dataset '{dataset}' from cleaned CSV columns",
    )


# --------------------------------------------------------------------------------------
# Parquet path resolution
# --------------------------------------------------------------------------------------


def _summary_logger_parquet_path(year: int, resolution: str) -> Path:
    return PARQUET_SUMMARY_DIR / resolution / f"{year}_{resolution}.parquet"


def _summary_logger_ratios_parquet_path(year: int, resolution: str) -> Path:
    return PARQUET_SUMMARY_DIR / resolution / f"{year}_{resolution}_ratios.parquet"


def _summary_weather_base_dir(resolution: str) -> Path:
    mapping: dict[str, Path] = {
        "15min": PARQUET_SUMMARY_WEATHER_15MIN_DIR,
        "hourly": PARQUET_SUMMARY_WEATHER_HOURLY_DIR,
        "daily": PARQUET_SUMMARY_WEATHER_DAILY_DIR,
        "monthly": PARQUET_SUMMARY_WEATHER_MONTHLY_DIR,
    }
    return mapping.get(resolution, PARQUET_SUMMARY_DIR / "weather" / resolution)


def _summary_weather_parquet_candidates(year: int, resolution: str) -> list[Path]:
    base = _summary_weather_base_dir(resolution)
    return [
        base / f"{year}_{resolution}.parquet",
        base / f"{year}_{resolution}_weather.parquet",
        base / f"weather_{year}_{resolution}.parquet",
    ]


def _logger_parquet_path(year: int, resolution: str) -> Path:
    preferred = _summary_logger_parquet_path(year, resolution)
    if preferred.exists():
        return preferred

    return PARQUET_DIR / str(year) / resolution / f"{year}_{resolution}.parquet"


def _logger_ratios_parquet_path(year: int, resolution: str) -> Optional[Path]:
    preferred = _summary_logger_ratios_parquet_path(year, resolution)
    if preferred.exists():
        return preferred

    old = PARQUET_DIR / str(year) / resolution / f"{year}_{resolution}_ratios.parquet"
    if old.exists():
        return old

    return None


def _weather_parquet_path(year: int, resolution: str) -> Optional[Path]:
    for c in _summary_weather_parquet_candidates(year, resolution):
        if c.exists():
            return c

    old_base = PARQUET_DIR / str(year) / resolution / "weather"
    old_candidates = [
        old_base / f"{year}_{resolution}_weather.parquet",
        old_base / f"{year}_{resolution}.parquet",
        old_base / f"weather_{year}_{resolution}.parquet",
    ]
    for c in old_candidates:
        if c.exists():
            return c

    return None

# --------------------------------------------------------------------------------------
# File reading helpers
# --------------------------------------------------------------------------------------


def _read_parquet_df(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise HTTPException(status_code=404, detail=f"Parquet not found: {path}")
    try:
        return pd.read_parquet(path)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to read parquet {path}: {e}")


def _read_workbook_sheet_df(sheet_name: str) -> pd.DataFrame:
    if not IRRIGATION_WORKBOOK_PATH.exists():
        raise HTTPException(status_code=404, detail=f"Workbook not found: {IRRIGATION_WORKBOOK_PATH}")
    try:
        return pd.read_excel(IRRIGATION_WORKBOOK_PATH, sheet_name=sheet_name, engine="openpyxl")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to read sheet {sheet_name}: {e}")


def _load_logger_download_df(year: int, resolution: str) -> pd.DataFrame:
    try:
        return load_logger_data(year=year, granularity=resolution)
    except FileNotFoundError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except ValueError as e:
        raise HTTPException(status_code=500, detail=str(e))
    except OSError as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to load logger data for year={year}, resolution={resolution}: {e}",
        )


def _load_weather_download_df(year: int, resolution: str) -> pd.DataFrame:
    try:
        df = load_weather_data(year=year, granularity=resolution)
    except ValueError as e:
        raise HTTPException(status_code=500, detail=str(e))
    except OSError as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to load weather data for year={year}, resolution={resolution}: {e}",
        )

    if df.empty:
        raise HTTPException(status_code=404, detail=f"No weather data found for {year} {resolution}")

    return df


def _zip_bytes(files: list[tuple[str, bytes]]) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        for name, content in files:
            zf.writestr(name, content)
    buf.seek(0)
    return buf.read()


# --------------------------------------------------------------------------------------
# Manifest
# --------------------------------------------------------------------------------------


@bulk_router.get("/bulk_download_manifest")
def bulk_download_manifest() -> dict[str, Any]:
    items: list[dict[str, Any]] = []

    years = _list_years_on_disk()
    for y in years:
        res_list = _list_resolutions_on_disk(y)
        for res in res_list:
            lp = _logger_parquet_path(y, res)
            if lp.exists():
                items.append(
                    {
                        "key": f"loggers_{y}_{res}",
                        "dataset": "loggers",
                        "year": y,
                        "resolution": res,
                        "label": f"Logger data ({y}, {res})",
                    }
                )

            wp = _weather_parquet_path(y, res)
            if wp is not None and wp.exists():
                items.append(
                    {
                        "key": f"weather_{y}_{res}",
                        "dataset": "weather",
                        "year": y,
                        "resolution": res,
                        "label": f"Weather data ({y}, {res})",
                    }
                )

    for dataset_key, (csv_path, label_base, _) in MANAGEMENT_DATASETS.items():
        if not csv_path.exists():
            continue

        items.append(
            {
                "key": f"{dataset_key}_all",
                "dataset": dataset_key,
                "year": None,
                "resolution": None,
                "label": f"{label_base} (all years)",
                "file_path": str(csv_path),
            }
        )

    if IRRIGATION_WORKBOOK_PATH.exists():
        try:
            xls = pd.ExcelFile(IRRIGATION_WORKBOOK_PATH, engine="openpyxl")
            sheets = [str(s) for s in xls.sheet_names]
        except Exception:
            sheets = []

        for base, token in WORKBOOK_TOKENS.items():
            for s in sheets:
                s_match = s.strip().upper()
                if token in s_match:
                    for part in s_match.replace("-", " ").replace("_", " ").split():
                        if len(part) == 4 and part.isdigit():
                            year = int(part)
                            break
                    if year is None:
                        continue
                    items.append(
                        {
                            "key": f"{base}_{year}",
                            "dataset": base,
                            "year": year,
                            "resolution": None,
                            "label": f"{base.title()} ({year})",
                            "workbook_sheet": s,
                        }
                    )

    for key, (label, p, _) in FILE_BACKED_DOWNLOADS.items():
        if p.exists():
            items.append(
                {
                    "key": key,
                    "dataset": "file",
                    "year": None,
                    "resolution": None,
                    "label": label,
                    "file_path": str(p),
                }
            )

    manifest_years = sorted({int(item["year"]) for item in items if item.get("year") is not None})
    manifest_granularities = sorted({str(item["resolution"]) for item in items if item.get("resolution")})

    return {
        "entries": items,
        "years": manifest_years,
        "granularities": manifest_granularities,
    }


# --------------------------------------------------------------------------------------
# Download
# --------------------------------------------------------------------------------------


@bulk_router.post("/bulk_download")
async def bulk_download(payload: dict[str, Any]):
    """
    Payload supports:
      - {"key": "loggers_2025_daily"}
      - {"keys": ["loggers_2025_daily"]}
    """
    keys = payload.get("keys")
    if isinstance(keys, list) and keys:
        key = str(keys[0])
    else:
        key = str(payload.get("key") or "").strip()

    if not key:
        raise HTTPException(status_code=400, detail="Missing key (or keys[0])")

    if key in FILE_BACKED_DOWNLOADS:
        dataset_label, p, zip_filename = FILE_BACKED_DOWNLOADS[key]

        if not p.exists():
            raise HTTPException(status_code=404, detail=f"File dataset not found on disk for key: {key}")

        try:
            df = pd.read_csv(p)
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Failed to read CSV for key {key}: {e}")

        csv_bytes = df.to_csv(index=False).encode("utf-8")
        readme = _file_backed_readme_text(
            dataset_label=dataset_label,
            source_path=p,
            df=df,
        )

        zip_bytes = _zip_bytes(
            [
                (zip_filename, csv_bytes),
                ("README.txt", readme.encode("utf-8")),
            ]
        )

        return StreamingResponse(
            io.BytesIO(zip_bytes),
            media_type="application/zip",
            headers={"Content-Disposition": f'attachment; filename="biochar_{key}.zip"'},
        )

    parts = key.split("_")
    dataset = parts[0].lower()

    files: list[tuple[str, bytes]] = []
    zip_name = f"biochar_{key}.zip"

    if dataset in {"loggers", "weather"}:
        if len(parts) < 3:
            raise HTTPException(status_code=400, detail=f"Expected {dataset}_YYYY_resolution key, got: {key}")

        year = _safe_int(parts[1])
        resolution = str(parts[2]).strip()

        if year is None:
            raise HTTPException(status_code=400, detail=f"Invalid year in key: {key}")
        if resolution not in ALLOWED_RESOLUTIONS:
            raise HTTPException(status_code=400, detail=f"Invalid resolution '{resolution}' in key: {key}")

        if dataset == "loggers":
            logger_df = _load_logger_download_df(year=year, resolution=resolution)
            csv_bytes = logger_df.to_csv(index=False).encode("utf-8")
            files.append((f"biochar_loggers_{year}_{resolution}.csv", csv_bytes))

            ratios_pq = _logger_ratios_parquet_path(year, resolution)
            ratios_included = False
            if ratios_pq is not None and ratios_pq.exists():
                ratios_df = _read_parquet_df(ratios_pq)
                ratios_bytes = ratios_df.to_csv(index=False).encode("utf-8")
                files.append((f"biochar_loggers_{year}_{resolution}_ratios.csv", ratios_bytes))
                ratios_included = True

            readme = _readme_text(
                "logger",
                year,
                resolution,
                notes=(
                    "Source loader: biochar_app.scripts.data_loading.load_logger_data\n"
                    f"Ratios included as separate file: {'yes' if ratios_included else 'no'}"
                ),
                df=logger_df,
            )

        else:
            weather_df = _load_weather_download_df(year=year, resolution=resolution)
            csv_bytes = weather_df.to_csv(index=False).encode("utf-8")
            files.append((f"biochar_weather_{year}_{resolution}.csv", csv_bytes))

            readme = _readme_text(
                "weather",
                year,
                resolution,
                notes="Source loader: biochar_app.scripts.data_loading.load_weather_data",
                df=weather_df,
            )

        files.append(("README.txt", readme.encode("utf-8")))

    elif dataset in MANAGEMENT_DATASETS:
        csv_path, dataset_label, filename_pattern = MANAGEMENT_DATASETS[dataset]

        if not csv_path.exists():
            raise HTTPException(status_code=404, detail=f"Management CSV not found: {csv_path}")

        try:
            management_df = pd.read_csv(csv_path)
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Failed to read management CSV {csv_path}: {e}")

        csv_bytes = management_df.to_csv(index=False).encode("utf-8")

        filename = (
            filename_pattern.format(year="all")
            if "{year}" in filename_pattern
            else filename_pattern
        )

        files.append((filename, csv_bytes))

        readme = _readme_text(
            dataset_label,
            None,
            None,
            notes=f"Source cleaned all-years management CSV: {csv_path}",
            df=management_df,
        )
        files.append(("README.txt", readme.encode("utf-8")))

    elif dataset in WORKBOOK_TOKENS:
        year = _safe_int(parts[1]) if len(parts) >= 2 else None
        if year is None:
            raise HTTPException(status_code=400, detail=f"Invalid year in key: {key}")

        try:
            xls = pd.ExcelFile(IRRIGATION_WORKBOOK_PATH, engine="openpyxl")
            sheets = [str(s) for s in xls.sheet_names]
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Cannot read workbook sheets: {e}")

        token = WORKBOOK_TOKENS[dataset]
        sheet = None
        for s in sheets:
            s_match = s.strip().upper()
            if token in s_match and str(year) in s_match:
                sheet = s
                break

        if not sheet:
            raise HTTPException(status_code=404, detail=f"No workbook sheet found for {dataset} {year}")

        workbook_df = _read_workbook_sheet_df(sheet)
        csv_bytes = workbook_df.to_csv(index=False).encode("utf-8")
        files.append((f"biochar_{dataset}_{year}.csv", csv_bytes))

        readme = _readme_text(
            dataset,
            year,
            None,
            notes=f"Source workbook: {IRRIGATION_WORKBOOK_PATH}\nSheet: {sheet}",
            df=workbook_df,
        )
        files.append(("README.txt", readme.encode("utf-8")))

    else:
        raise HTTPException(status_code=400, detail=f"Unknown dataset in key: {key}")

    zip_bytes = _zip_bytes(files)

    return StreamingResponse(
        io.BytesIO(zip_bytes),
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{zip_name}"'},
    )